### ISSUE TITLE
Automatic docker server URI resolution

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#100]
In order to simplify the configuration of docker server IP, Arquillian Cube could provide a default strategy for resolving it. In case no serverUri property is set, Cube will do next thing:

if Win or OSx then makes resolution of boot2docker ip (see #99 .
if linux uri will be unix://var/lib/docker/docker.sock

**Comment by aslakknutsen** [comment]
Once that is resolved, one should be able to invoke url/version to auto set the api version to use as well.
