### ISSUE TITLE
Print/Log all events to console, if resources are not in ready state

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-cube#1001]
Currently there is no way to see what's going on if resources are not in ready state. We are throwing message.

It'll be good if we print all events to console using `oc get events -w`. So user will get to know in first run itself what's going wrong. Instead of rerunning test again.

**Comment by bartoszmajsak** [comment]
Thanks @dipak-pawar. That can be helpful. Can you elaborate on how this should be enabled? Some pointers to the code base where this can be invoked might help too.

**Comment by dipak-pawar** [comment]
Looks for is there any functionality present in client to log events. if yes then use it. otherwise we can add that feature to upstream or use `oc  get events -w` using [`CommandExecutor`](https://github.com/arquillian/arquillian-cube/blob/master/kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/utils/CommandExecutor.java#L10) for now.

Codebase- https://github.com/arquillian/arquillian-cube/blob/master/kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java#L185

**Comment by lordofthejars** [comment]
Be aware of using `oc` since it implies that it is installed on host machine and that maybe the test is running against a Kubernetes cluster.
