### ISSUE TITLE
Update Istio support to 0.8.0

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#1062]
##### Issue Overview

Update Istio support to 0.8.0

##### Expected Behaviour

Be able to use Istio 0.8.0

##### Current Behaviour

Only support for 0.7 or old

**Comment by lordofthejars** [comment]
https://github.com/arquillian/arquillian-cube/pull/1060

**Comment by metacosm** [comment]
@lordofthejars do you still require support for `0.7.1` and older resources? I'm considering updating the Istio Java API to minimally require `0.8` to simplify things.

**Comment by lordofthejars** [comment]
@metacosm for me you can remove it. Everyone should migrate to 0.8
