### ISSUE TITLE
CircleCi builds do not work

### ISSUE THREAD

**Issue by TheOnlyAl** [arquillian/arquillian-cube#1255]
##### Issue Overview

Currently the circleci builds of this repository fail to build. Also the travis builds seem to not work since travis or Arquillian changed something.

##### Expected Behaviour

Builds are done for Commits / PRs on circleci to check if the code changes are okay.

##### Current Behaviour

The builds fail.

##### Steps To Reproduce
1. Commit something
2. Builds fail

##### Additional Information

I idendtified some problems with the builds related to the rather complex (at least for me) setup of the tests and the incomplete setup of the circleci builds. For example:

- JDK 11 builds are currently not working since some problems with old libraries like https://github.com/sundrio/sundrio/tree/main/annotations
- JDK 8 builds fail since some of the tests require a running docker environment just for the test if they should run even without docker
- Integration tests need also a running Kubernetes and Openshift setup. Which was done for travis but not for circleci

Since i plan to do maybe do some work and PRs in the future i would like to have the builds work at least a little bit. :)

**Comment by gtudan** [comment]
I agree that we should first get at least some level of CI-Feedback before continuing to work on this. 
So getting at least JDK 8 builds back would be a big step 👍
