### ISSUE TITLE
Upgrade io.fabric8 archives to version 6.9.2

### ISSUE THREAD

**Issue by rsearls** [arquillian/arquillian-cube#1288]
arquillian-cube:1.18.3-SNAPSHOT was using io.fabric8:*:4.0.3.
  Package names in version 4.0.3 all had names containing the string
  "v4_0".  (e.g. io.fabric8.kubernetes.api.model.v4_0.Namespace) 
  io.fabric8:*:5.x.x is mostly 4.0.3 code with "v4_0" removed
  from the package names.  There are a few classes with code changes
  to be considered.  io.fabric8:*:6.x.x has significant code changes.
  So much so that a migrations guide has been provided.
  https://github.com/fabric8io/kubernetes-client/blob/main/doc/MIGRATION-v6.md
  Upgrading to io.fabric8:6.9.2 will required extensive evaluation and changes
  to code in module kubernetes.kubernetes.
  
  Here is the list of io.fabric8 archives arquillian-cube references.
      io.fabric8:kubernetes-openshift-uberjar
      io.fabric8:kubernetes-client
      io.fabric8:openshift-client
      io.fabric8:kubernetes-client-api

This issue depends on https://github.com/arquillian/arquillian-cube/issues/1270
being resolved first.
See tracker doc, https://github.com/arquillian/arquillian-cube/issues/1279

**Comment by rsearls** [comment]
Closing as duplicate of 
https://github.com/arquillian/arquillian-cube/issues/1269
https://github.com/arquillian/arquillian-cube/pull/1275

**Comment by fabiobrz** [comment]
> Closing as duplicate of #1269 #1275

Let's close the issue, as mentioned by the OP in the quoted comment.
