### ISSUE TITLE
ImagesAssert resolve version upgrade class parameter changes.

### ISSUE THREAD

**Issue by rsearls** [arquillian/arquillian-cube#1289]
[ERROR] /home/rsearls/j1/arquillian-cube/docker/assertj/src/main/java/com/github/dockerjava/assertions/ImagesAssert.java:[26,9] method assertThat in class org.assertj.core.api.FactoryBasedNavigableListAssert<SELF,ACTUAL,ELEMENT,ELEMENT_ASSERT> cannot be applied to given types;
[ERROR]   required: java.util.List<? extends ELEMENT>,org.assertj.core.api.AssertFactory<ELEMENT,ELEMENT_ASSERT>
[ERROR]   found: java.util.List<capture#1 of ? extends com.github.dockerjava.api.model.Image>
[ERROR]   reason: cannot infer type-variable(s) ACTUAL,ELEMENT,ELEMENT_ASSERT
[ERROR]     (actual and formal argument lists differ in length)

This issue depends on https://github.com/arquillian/arquillian-cube/issues/1270
being resolved first.
See tracker doc, https://github.com/arquillian/arquillian-cube/issues/1279

**Comment by fabiobrz** [comment]
Solved in https://github.com/arquillian/arquillian-cube/pull/1296/files#diff-5c88e0bd31cb85f1226b4b32f220834e49b7d9840a620073c6f9add66a53d9d8R24

FYI @rsearls

**Comment by rsearls** [comment]
Resolved by https://github.com/arquillian/arquillian-cube/issues/ Bumping Fabric8 version to 6.9.2
