### ISSUE TITLE
Adds return type check for autobinding algorithm

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#140]
Adds return type check for autobinding algorithm. For example there are some adapters that uses a method called `exportConfiguration` which returns a boolean. Because it contains the substring port, we try to make a cast to integer and a classcastexception occurs.

**Comment by aslakknutsen** [comment]
Possible tighten the regExp there as well. if starts with 'port' or ends with 'Port' ?

**Comment by lordofthejars** [comment]
yes and no, if the property is called configurationExport it ends with port too. and what's happening if the property is called ajpPorts for example. I think that if we start with too restrictive reg exp. we are going end up by adding a lot of exceptions.  I have found this error in TomEE, and for now this fixes it.

**Comment by aslakknutsen** [comment]
:+1:
