### ISSUE TITLE
Creates bom file for Cube

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#158]
If you want to use containerless feature you need to import two dependencies one the cube-docker and another one the containerless dependency. To avoid users using different versions could be interesting to do like drone or shrinkwrap and create a bom file. Moreover when we start with Mesos, Marathon, Openshift, Kubernetes and so on, so it can be really useful to maintain all versions in one.

**Comment by aslakknutsen** [comment]
I think we can say Cubes BOM is via the Universe BOM?

**Comment by lordofthejars** [comment]
Yes
