### ISSUE TITLE
Make autoStartContainers regular expression aware

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#161]
autoStartContainers is a property where you specify which containers must be started before the application/main container is started. Currently it supports a comma-separated list, so if you need to start two containers you can do it as `A, B`. This is ok for a few containers but in cases you want to start more than once, for example one email server, one database server, one key-value server, then it needs more work. Also if you change the name of the container then the test will fail because the container won't be started.

To avoid this scenario we can apart from supporting comma approach using regular expression approach, so you can do something like `^((?!tomee).)*$` which means it will autostart all containers except the one tagged as tomee.

**Comment by aslakknutsen** [comment]
This sounds reasonable.

Another approach we could look into as well is:

* Auto start linked containers to 'managed' container

**Comment by lordofthejars** [comment]
So true I will implement this in a separate issue and be the default
strategy to use.
El dt., 28 de jul., 2015 a les 19.10 Aslak Knutsen <notifications@github.com>
va escriure:
