### ISSUE TITLE
Support for ContainerObject pattern

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#167]
Similar to PageObject pattern we could provide something that I call ContainerObject pattern which is an object representation of the container so you can interact with the container in a reusable way (as PageObject does with WebDriver)

**Comment by aslakknutsen** [comment]
How is this different from the ContainerController?

Or are you simply thinking;

```java
public class MyController {
  @Cube
  private ContainerController cc;

  public void doCommonTask() {
    cc.x()
  }
}

public class MyTestCase {
   @Cube
   private MyController mc;

   @Test
   public void shouldX() {}
}
```

?

**Comment by lordofthejars** [comment]
Yes I am thinking in using the same concept of PageObjects of Graphene (more or less) I mean yo can do the same of Graphene (PageObject) with Drone, simple annotate with `@Drone` a test and that's all, you can start interacting with the browser, but for reusing you use PageObjects, this concept is exactly the same I want to inject a Cube and with an Id having there:

```
@Cube("my_autostarted_container")
CubeID containerId;

@Cube
ContainerController cc;

public int[] getPortBindings() {
...
}
public String dockerHostIp() {
...
}

//... more operations related with containers
```

My idea behind this and I will continue explaining in #168 is that suppose you have a piece of code not necessary to run inside a web container that sends an email. So one way to write the test could be creating a normal junit, but using Cube to start a mailing server, so this is using Arquillian-Cube-Standalone. In that cases your logic would require the ip and the port of the server, so instead of hardcoding in the test (since ip can change if you are using boot2docker or not, I think this information is stored in Binding class), you can create your containerobject who deals with all the operations like getting this information. This also improves the reusability since you can have a jar file with all this information, so anyone who needs a mailing server for its test only needs to import a jar file and that's all, it can start annotating its test. And this links to the issue #168 .

**Comment by lordofthejars** [comment]
I want to add some examples of how a Container Object would look like:

```java
@Image("tomcat")
public class Tomcat  {
 @ArquillianResource
 private HostIp hostIp;

 @ArquillianResource
 private Bindings bindingPorts;

}
```
You can define a Cube using `@Image` to set the image to be used. And also `@ArquillianResource` for getting HostIp and binding ports of this cube.

```java
@Dockerfile(location = "src/test/resources")
public class CustomTomcat {
//....
}
````
Creates a Cube image from a directory that contains a Dockerfile.

```java
public class CustomTomcat {

  @Dockerfile
  public static GenericArchive<?> createCube() {

  }
}
```

Creates a cube from a Dockerfile located at root of genericarchive. This Dockerfile can be created using the Dockerfile Descriptor. It is a GenericArchive because a Dockerfile may require some extra files (ADD) to work. This generic archive will be materialized to tmp directory.

To use it inside a test you simply need to do this:

```java
@Cube(name = "mytomcat", ports = {"8081 -> 8080", "443"})
Tomcat tomcat;
```

**Comment by aslakknutsen** [comment]
How about some form of 'Provider' API to programmatically register the Cubes instead of recreating the whole cube yaml format in Annotations? 

e.g. 

```java
// Registration
public class MyMailCubeProvider implements CubeProvider {
	
	public void provide(CubeRegistrer reg) {
		reg.register(
			"mail-server",
			MailServer.class,
			Descriptors.create(CubeDockerDescriptor.class)
				.image("mail")
				...);
	}	
}

public class MailServer {
	@ArquillianResource
	private HostIP hostIp;

	public URL getURL() {
		return new URL(hostIp.getIP());
	}
}

// Usage

public class MailTestCase {
	@Cube
	MailServer mail;

	@Test
	public void shouldSendEmail() {
		// do something
		mail.getURL();
	}
}
```

Technically we could use the same Descriptor as from #74, just a different use case/ registration process.

**Comment by lordofthejars** [comment]
Does the Provider means creating a `META-INF/services` file or you named Provider because it is a Provider but not a JDK service provider? I like you approach anyway :)

:alien:

**Comment by aslakknutsen** [comment]
> Does the Provider means creating a META-INF/services file or you named Provider because it is a Provider but not a JDK service provider? I like you approach anyway :)

Provider was just a name. How these are discovered is up to the impl :)

**Comment by lordofthejars** [comment]
The port should be still possible to set in the `Cube` annotation as well as name. So it is possible to use same image in several instances for clustering testing. So in this case I am not sure how your solution might suite.

**Comment by aslakknutsen** [comment]
Right, the @Cube in your example was the usage. I read that as a short-hand registration. 

My solution would be a replacement to @Dockerfile on class/method level.

But how would @Cube(name = "mytomcat", ports="") work? Is each injection point a new instance of a Cube based on "mytomcat" as a template?

**Comment by lordofthejars** [comment]
My idea is when I found `@Cube` annotation I use the class definition to know which image I need to start (or build prior to start), and then with `@Cube` I give the name and the ports. Nothing more, the idea is not to provide a full support of yaml, but only the basic things we may need (and if anyone opens an issue then add it).

Then with `@Cube` and the class create a container definition that will be used by autostart logic.

**Comment by aslakknutsen** [comment]
How do you deal with the following code in the same run?

```java
public class TomcatTestCase {
	@Cube("mytomcat", ports = ["1"])
	Tomcat test;

}

public class TomcatOtherTestCase {
	@Cube("mytomcat", ports = ["2"])
	Tomcat test;

}
```

**Comment by lordofthejars** [comment]
Docker Host will complain because it cannot create two instances with same name. You should do:

```java
public class TomcatTestCase {
    @Cube("mytomcat-1", ports = ["1"])
    Tomcat test;

}

public class TomcatOtherTestCase {
    @Cube("mytomcat-2", ports = ["2"])
    Tomcat test;

}
```

**Comment by aslakknutsen** [comment]
Right, so each @Cube results in a CreateCube event?

And if you have multiple @Cube(id, port=[different ports]), Docker will complain eventually and the user is silly for trying?

**Comment by lordofthejars** [comment]
Exactly

**Comment by aslakknutsen** [comment]
In my mind that is very bad.. 

That would result in a test suite random failing due to order of TestClass execution... ?

**Comment by lordofthejars** [comment]
why? I mean in BeforeSuite I will create everything and autostart will start all containers. After that everything will be as a standard Cube test.

**Comment by aslakknutsen** [comment]
You want to scan all TestClasses in BeforeSuite then?

**Comment by lordofthejars** [comment]
not all, only the ones defined in the test class under execution.

El dl., 21 set. 2015 a les 18:04, Aslak Knutsen (<notifications@github.com>)
va escriure:

**Comment by lordofthejars** [comment]
Something like @Page of Graphene but for Cube
El dl, 21 set 2015 a les 18:07 Alex Soto <asotobu@gmail.com> va escriure:

**Comment by aslakknutsen** [comment]
Right, but unless we do some custom classpath scanning in Cube, you won't know what test classes are to be executed in BeforeSuite. You will know them one by one in BeforeClass first.

**Comment by lordofthejars** [comment]
humm Iso true I thought that I would be able to get test class in BeforeSuite. The problem with BeforeClass is that autostart has been already executed. Yes probably we will need to do what you mention. xbean-finder can help us a lot.

**Comment by lordofthejars** [comment]
After more discussions we agreed with next code:

```
public class Test {
 
@Cube("service1")
Service service;
 
}
 
public class Service {
 
        @CubeDescriptor
        public static Archive<?> service() {
                return ShrinkWrap.create(GenericArchive.class)
                        .add(new ClassloaderResource("my_file.txt"), "my_file.txt")
                        .add(
                                Descriptors.create(CubeDescriptor.class)
                                .build(
                                        Descriptors.create(DockerDescriptor.class)
                                                .from("tomcat")
                                                .add("my_file.txt")
                                )
                        )
        }
 
        @Cube("mysql_1")
        private Backend backend;
 
}
 
public class Backend {
 
        @CubeDescriptor
        public static CubeDescriptor backend() {
                return Descriptors.create(CubeDescriptor.class)
                        image("database");
        }
 

```

**Comment by lordofthejars** [comment]
```
public class Backend {
 
        @CubeDescriptor
        public static CubeDescriptor backend() {
                return Descriptors.import(CubeDescriptor.class).from("....");
        }
 
}
```

**Comment by lordofthejars** [comment]
It is going to be implemented as test enricher to start and afterclass to stop:

````public class CubeTestEnricher implemnets TestEnricher {
        @Inject Instance<ServiceLoader> serviceLoader;
 
        public void enrich(Object instance) {
                for each field with @Cube in instance.class
                        enrichCube(createInstance(field))
        }
 
        public void enrichCube(Object instance) {
                enrichmentEvent.fire(new BeforeEnrichment());
                Collection<TestEnricher> testEnrichers = serviceLoader.get().all(TestEnricher.class);
                for(TestEnricher enricher : testEnrichers)
                {
                        enricher.enrich(instance);
                }
                enrichmentEvent.fire(new AfterEnrichment());
        }
       
}
```

**Comment by lordofthejars** [comment]
@Cube id is not mandatory and if is not provided  random one is chosen.

**Comment by lordofthejars** [comment]
public class Test {
 
        @Cube("service1")
        Service service;
 
}
 
@CubeDockerFile('_class_path_resource')
public class Service {
 
}
