### ISSUE TITLE
Add fixture support

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#168]
We could add fixture support in the sense that instead of defining containers in arquillian.xml we could define them with annotation on ContainerObject pattern. See #167 for info about this pattern.

**Comment by aslakknutsen** [comment]
This sounds similar to https://github.com/arquillian/arquillian-cube/issues/74 ?

**Comment by lordofthejars** [comment]
Now we have a containerobject that represents a operations that you can do to a container for a purpose (for example getting the dockerHostIp to communicate, ports, cube operations, ...) but to be self-contained it we would require that this containerobjects can be started automatically as well without any definition. For this reason I think that we need to add the fixtures feature.
For example:

```
package a.b;

@WithCubeFixture
public class A {
}
```

In this case when starting cube we inspect for classes on classpath annotated with `@WithCubeFixture` and if it is the case then it takes from classpath a/b/ the Dockerfile and builds the image.

And of course if WithFixture is not present we can see for an static method annotated with @Dockerfile which creates the Dockerfile using Shrinkwrap.

So now a ContainerObject is effectively a reusable piece where you can bundle with its own jar file and reuse across all the projects.

**Comment by lordofthejars** [comment]
One question for fixing this issue I would like to scan the classpath searching for classes that are annotated with `@WithCubeFixture`. I know that to accomplish this in Apache TomEE, xbean library is used. Any other suggestion?
