### ISSUE TITLE
PollingAwaitStrategy: polling problem with ss command on Windows

### ISSUE THREAD

**Issue by foxlegend** [arquillian/arquillian-cube#181]
Hi there,

When executing an Arquillian test case on Windows with the Cube extension I had a problem with the polling strategy: polling limit was reached and Cube raised an exception as it was unable to connect to my container.
I took a look at my docker daemon logs, and I found such lines:

    time="2015-10-05T14:38:39.352198042Z" level=debug msg="Calling POST /containers/{name:.*}/exec"
    time="2015-10-05T14:38:39.352238525Z" level=info msg="POST /v1.20/containers/jbossas/exec"
    time="2015-10-05T14:38:39.362334001Z" level=debug msg="Calling POST /exec/{name:.*}/start"
    time="2015-10-05T14:38:39.362387345Z" level=info msg="POST /v1.20/exec/100722dc8c81731b53aee9b11ac42a676d5803ff9559a1b5e17db4b5dec6393a/start"
    time="2015-10-05T14:38:39.363428060Z" level=debug msg="starting exec command 100722dc8c81731b53aee9b11ac42a676d5803ff9559a1b5e17db4b5dec6393a in container fd471659bf523c0aaebe933ef157779d7c932f291480a031a275263900a816ec"
    time="2015-10-05T14:38:39.363579706Z" level=debug msg="attach: stdout: begin"
    time="2015-10-05T14:38:39.459238430Z" level=debug msg="Exec task in container fd471659bf523c0aaebe933ef157779d7c932f291480a031a275263900a816ec exited with code 1"
    time="2015-10-05T14:38:39.459315737Z" level=debug msg="attach: stdout: end"
    2015/10/05 14:38:39 http: response.WriteHeader on hijacked connection

I found that the command in `ss.sh` was executed: `ss -lntu | grep '${port}' | grep LISTEN -c`, and the template was built thanks to the `org.arquillian.cube.docker.impl.util.IOUtil` class, with the offending function:

```java
    public static String asStringPreservingNewLines(InputStream response) {
        StringWriter logwriter = new StringWriter();

        try(BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(response))) {

            String line = null;
            while ((line = bufferedReader.readLine()) != null) {
                logwriter.write(line);
                logwriter.write(System.lineSeparator());
            }

            return logwriter.toString();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

It uses `System.lineSeparator()` to append the EOL to the template, but as I am on Windows it results in `\r\n` giving something like `ss -lntu | grep '8080' | grep LISTEN -c\r\n` executed in my container with the `exec` endpoint. As a result bash is not able to interpret such EOL: the command returns a `1` status code (error) instead of the expected result, and polling strategy tries a new iteration giving the same result until the maximum number of iterations is reached.

When shadowing the class by "patching"  and replacing `System.lineSeparator()` with an hardcoded `\n`, everything is working as expected.

I do not know what kind of fix or workaround would be better…

**Comment by lordofthejars** [comment]
Hi first of all thank you so much for using Cube and more important using windows since we have not been able to test it in Windows. I think that the best way to proceed would be creating a constant  value and fix it as Linux/MACOs value and add a comment saying why this is with this value. Of course PR is more than welcome.

Again thank you so much for your help.

cc/ @aslakknutsen 

@myfear: it seems that it works in Windows, maybe you had exactly the same problem.
