### ISSUE TITLE
Some docs improvments

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-cube#222]
JAVA_OPTS=-Djava.rmi.server.hostname=localhost 

Should recommend using dockerServerIp instead of localhost

    <property name="host">${docker.tomcat.host}</property>
    <property name="httpPort">8081</property>

Should technically be removed due to auto configuration, tho concept is explained later in the doc.
(also #221)  

    <property name="managementPort">9991</property>

Should be removed as it will be handled by Cube

    <property name="containerlessDocker">node</property> (1)
    <property name="embeddedPort">8080</property>

Could be removed, but the rules around defaulting to the one Cube and the first port should be described.

**Comment by lordofthejars** [comment]
Done. In my repo you can see the changes in README.adoc, I will send the PR as soon as you review the changes :)
