### ISSUE TITLE
I want to use events even I use docker-compose 

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#253]
It seems to me that beforeStop and similar events are treated only in CUBE definition format. I would like to pull something from machines in case I am using COMPOSE definition format as well but I do not think that I can mix these two.

Is there a way how do to this or I just do that via DockerClientExecutor?

**Comment by lordofthejars** [comment]
No you cannot mix now.

**Comment by aslakknutsen** [comment]
@smiklosovic You should be able to use the CubeController for that, but not automated. Same root cause as #254
