### ISSUE TITLE
I would like to use system properties in dockerContainers property

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#258]
Sorry if this is already possible but I noticed you are about the release and I do not want to miss this.

My issue is that I would like to expand system properties in dockerContainers property. Something roughly like this:

````
<property name="dockerContainers">
    tomcat:
        image: tutum/tomcat:7.0
        binds:
            - ${dir.on.host}:/container:ro
</property>
````

The reason behind this is that I am going to execute these tests by Spacelift Gradle plugin where I set System property to the process which executes them and I want to be pretty flexible as from where some container will pick its configuration which I will likely build locally before mounting that host dir to to-be-started container.

I saw you are doing this already in DockerfileTemplate so expanding this feature to this property should not take a lot of effort.

**Comment by lordofthejars** [comment]
If you use Docker-Compose format it is already implemented in all properties:

https://github.com/arquillian/arquillian-cube/issues/188
https://github.com/arquillian/arquillian-cube/issues/243

In custom CUBE format I should take a look if it is possible to implement it easily or not.

**Comment by smiklosovic** [comment]
I can not use docker compose, I will look into this. Thanks for info.

**Comment by aslakknutsen** [comment]
It should be handled by core already. If I remember correctly we do sys
prop replacement on the whole XML file as a string.. :)

**Comment by smiklosovic** [comment]
I have tried it and it works as Aslak suggested.
