### ISSUE TITLE
Cube 1.0.0.Alpha8 can not parse images from custom registry in configuration

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#265]
@aslakknutsen @lordofthejars 

I was on Alpha7 for a long time and today I migrated to Alpha8

All was good in Alpha7 but now, I am not able to start any container which image is from private image repository, even I have that image stored locally.

I have it like this:

````
<property name="dockerContainers">
    service:
        image: docker.some.company:5000/company/service:1.0.0
</property>
````

But when I look into the output which is being printed out while test is executing of the dockerContainers resolved property, it says that image is this:

````
image: docker.some.company:5000/company/service
````

Note that there is tag missing. It fails on the exception that it was not able to found `docker.some.company:5000/company/service`  which is true.

This is basically the same thing as was discussed few days ago. It seems to me you do not handle the parsing of the image right.

**Comment by lordofthejars** [comment]
It will be fixed in alpha9
https://github.com/arquillian/arquillian-cube/pull/264
<https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Farquillian%2Farquillian-cube%2Fpull%2F264&sa=D&sntz=1&usg=AFQjCNG_SLRJZxACEW7QUBqIMLh9OfpFgg>

**Comment by lordofthejars** [comment]
https://github.com/arquillian/arquillian-cube/pull/264 was merged.
