### ISSUE TITLE
I am getting connection resets when trying to use docker machine

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#267]
@lordofthejars  @aslakknutsen 

I followed all what is in the documentation. I have machine started, no containers there, ip of machine is used in arquillian.xml, I have set machineName to my virtual box docker machine,

This is exception:

http://pastebin.com/raw/u3kCcFiM

This is more or less arquillian.xml

````
    <extension qualifier="docker">
        <property name="serverVersion">1.21</property>
        <property name="serverUri">https://dockerHost:2376</property>
        <property name="dockerRegistry">some registry</property>
        <property name="username">user</property>
        <property name="password">pass</property>
        <property name="email">some@mail</property>
        <property name="definitionFormat">CUBE</property>
        <property name="machineName">dev</property>
        <property name="dockerContainers">
            tomcat:
                image: some image
                exposedPorts: [1099/tcp,8000/tcp,8080/tcp,8009/tcp]
                await:
                    strategy: polling
                    type: static
                    ip: <external ip of the virtualbox machine>
                    sleepPollingTime: 5 s
                    iterations: 15
                portBindings: [1099/tcp,8000/tcp,8080/tcp,8009/tcp]
        </property>
    </extension>
````

It is possible to use CUBE format in case I am using docker machine?

I am not sure what should be in that ip field in await block but I think I have it right. Do you have a clue what could be the possible cause of  that error? Any hint? Some idea?

**Comment by lordofthejars** [comment]
This line can be removed and will be automatically set by Cube: ` <property name="serverUri">https://dockerHost:2376</property>`

**Comment by lordofthejars** [comment]
but not sure if your problem is in docker machine connection or not.

**Comment by smiklosovic** [comment]
Huh, as it turned out, there is not "static" type in polling strategy. Only "ping" or "ss". I changed type to ping and it works but in the documentation there is:

"Note that ping only works if you are running Docker daemon on localhost. "

**Comment by smiklosovic** [comment]
@lordofthejars 

you know what would be cool? If I have this waiting strategy, I have it like this:

````
await:
    strategy: polling
    type: static
    ip: 192.168.99.100
    sleepPollingTime: 5 s
    iterations: 15
````

But when you think about that, I have, effectively, the same IP in string which gets replaced by dockerHost in serverUri.

It would be cool if, in case there is some docker machine about to start and dockerHost is replaced, that ip in await strategy block would be automatically replaced as well, because right now I have to set it there explicitly and it is just not flexible when it changes.

**Comment by lordofthejars** [comment]
ip attribute is not in await strategies
