### ISSUE TITLE
Add Integration with Jenkins Traceability Plugin

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#271]
Add integration with https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Traceability so when a test is executed, the image is notified that has been used for testing purposes.

**Comment by aslakknutsen** [comment]
You want to notify of images Cube built as well?

**Comment by lordofthejars** [comment]
@aslakknutsen I am not sure if it has sense to notify the built ones, since these images are not going to be used in production but only built for testing purposes. The main focus of this plugin is to know which images are in production and the history they has been followed.

**Comment by lordofthejars** [comment]
After talking with my mates we decided that the best way to proceed with this is not implementing in Cube, but using one program provided by Docker Traceability Plugin which listens for Docker host events and do all the job. So when image is created by cube, the listener will detect and register in Jenkins.
This also ensures fully compatibility and less code to manage.

**Comment by aslakknutsen** [comment]
How do you know which are created/used by this test run? Compare time?

**Comment by lordofthejars** [comment]
WellI have talked wth people from solutions about this use case. They have told me the next. First that since it is traced the container, the docker traceability plugin knows which build has done this container so for each run the event manager will notify that the container with id X has been started and he knows that container X was created by job Y, so in this way we have fixed this. Then it comes my next question, how do you know that container X has been started for testing purposes? The answer I have received is that usually clients have different docker hosts so they know by the host.

Another advantage of this approach is that we don't really need to worry about API updates.  The daemon is provided in each release so it is going to be released with latest API support.

What we could do in the future is that if this event manager is ever released as docker container, we can run it automatically (or let user decide) but maybe this is another story that for now it is not done.
