### ISSUE TITLE
New Await strategy: Await ping service

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-cube#283]
In lights of 'ss' seemingly being removed from all over the place to align the content of base docker images, I think we can expect ss to be more and more un available in the future: 
https://github.com/jboss-dockerfiles/base/issues/5

A possible await strategy could be to deploy a minimal container that can ping the target containers from inside the machine/host.

* Create/Start a Arquillian Ping container
* Create/Start the configured N containers
* Communicate with the Ping container
    * http://ping/internal_container_ip/ports...

Of course, the question remains, when do we know the Ping container is up and running? I guess we could create a resilliant await client that can attempt a few times before failing. With a minimal sized image it shouldn't take long to start the service.

**Comment by lordofthejars** [comment]
how about trying other commands that runs pretty similar as `ss`? Do you think all of them are going to be removed? Also I am still see two options:

1) user need to create a dockerfile that installs ss.
2) we can install it by letting user set the command to execute to install it.

**Comment by smiklosovic** [comment]
maybe this is the right time to incorporate propper api for connection checks on application layer, afaik port binding done doesnt necessary mean the target app under test is fully running

**Comment by smiklosovic** [comment]
i have connection checks on tcp and udp layer based on spacelift reexecution feature of connection tasks, could not that just be called repeatedly until successful connection or timeout?

**Comment by lordofthejars** [comment]
This is the polling strategy right?

**Comment by aslakknutsen** [comment]
A Health API Ping would be a common strategy.

**Comment by lordofthejars** [comment]
we can use https://github.com/vishnubob/wait-for-it but this implies copying that file into container and execute it. This change could be related with https://github.com/arquillian/arquillian-cube/issues/333

**Comment by lordofthejars** [comment]
@aslakknutsen can I close this issue with won't fixed since now we can register custom await strategies?

**Comment by aslakknutsen** [comment]
@lordofthejars Sure, but maybe create a new one for e.g. 'HTTPAwaitStrategy' that can verify a HTTP response by content/status code ?
