### ISSUE TITLE
Any idea how to incorporate Recorder to Cube?

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#287]
I am just wondering if there is any specific feature you would like to see in Recorder when added to classpath while Cube is in charge.

Maybe there could be events listening on After/Before Cube Started/Stopped/Created or something similar which would appear in the final log.

Maybe logs from container could be appended to the final report as well? I can imagine that e.g. you would get dump of catalina.out or basically any file you want so you would know what happened there.

Any other idea is highly welcome!

**Comment by aslakknutsen** [comment]
Yea, good question. Adding some of the configuration and I guess the lifecycle events would be a start.

This issue is semi related: https://github.com/arquillian/arquillian-cube/issues/271

**Comment by lordofthejars** [comment]
Basically it means creating the events in SPI and modify this class https://github.com/arquillian/arquillian-cube/blob/master/core/src/main/java/org/arquillian/cube/impl/client/CubeLifecycleController.java to fire the events right?

And add only this

```
@Inject
    private Event<CubeStarted> startedEvent;
```

**Comment by lordofthejars** [comment]
Wait Wait this is what we want right? https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/model/DockerCube.java#L99 So we do not need to do anything. It is already there.

**Comment by aslakknutsen** [comment]
It might be easier to have as a Observer that observes the After/Before Cube events. That would allow us to dynamically add the Observer only if Recorder is on classpath and not bind Cube to the Reporter/Recorder

**Comment by lordofthejars** [comment]
Yes agreed but this observer should be in its own module, but the events
are already developed. It is a matter of implementing observers

**Comment by aslakknutsen** [comment]
I think we should do as we do with containers. As it to Cube core as a provided dependency. Recorder is added by user. It's so so many ways to configure recorder already

**Comment by lordofthejars** [comment]
yes, so it is a new module in Cube which if users add in the classpath then
everything is recorded.

El dt., 9 febr. 2016 a les 17:45, Aslak Knutsen (<notifications@github.com>)
va escriure:

**Comment by aslakknutsen** [comment]
I was arguing the opposite, keep it in core. A single observer that is
loaded if recorder is on class path. Core it self does not exist recorder
as a dependency.

That will allow the user to configure Cube and add recorder on will and not
have to add Cube-recorder as well.

**Comment by lordofthejars** [comment]
Right, good idea, at the end but they are still need to add a dependency.
And of course it should be implemented at core.

Stefan are you going to implement it or provide an example to follow to
implement it?
