### ISSUE TITLE
Building of node container in test fails

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#290]
This one is weird

http://pastebin.com/raw/7AfXTS9q

It behaves same if I use docker-java 2.1.4 or 2.1.3. I am on Docker 1.10.1 on Centos 7.2.1511. I have updated serverVersion from 1.12 to 1.22 and it is the same thing.

I have DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock"

Workaround is found here http://git.eclipse.org/c/linuxtools/org.eclipse.linuxtools.git/commit/?id=2bd239c34dd8201e72b1bfe9880026018d6b19b8

https://bugs.eclipse.org/bugs/show_bug.cgi?id=484344

https://github.com/golang/go/issues/9763

**Comment by smiklosovic** [comment]
I will work on this here

https://github.com/smiklosovic/arquillian-cube/tree/hijack

**Comment by smiklosovic** [comment]
I am still on Alpha7 and it behaves weird with Docker 1.10.1. All was good with 1.9 but with 1.10.1, there are various hangouts and timeouts, e.g. it can not stop already running containers and it stops basically on this:

````
(E) StopCube
    (O) CubeLifecycleController.stop
    (E) BeforeStop
        (O) BeforeStopContainerObserver.processCommands
````

so in the end it hangs on this in DockerClientExecutor.java

this.dockerClient.stopContainerCmd(containerId).exec();

Maybe it is related to this issue.

@aslakknutsen @lordofthejars 

Could somebody verify that it hangs with 1.10.1 please?

**Comment by lordofthejars** [comment]
Sorry I am in 1.9 now

**Comment by smiklosovic** [comment]
I can confirm that it works with current cube and 1.10.1. I am wondering what is wrong with Alpha7 or Alpha7 and Docker 1.10.1 that it does not play well.

**Comment by lordofthejars** [comment]
Maybe java-docker client version?

El dt., 16 febr. 2016 a les 12:03, Štefan Miklošovič (<
notifications@github.com>) va escriure:

**Comment by lordofthejars** [comment]
There was a problem that serverUri was not set correctly. Test has been fixed.
