### ISSUE TITLE
docker-machine distribution names change

### ISSUE THREAD

**Issue by eddumelendez** [arquillian/arquillian-cube#296]
v0.6.0
https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-Darwin-x86_64

v0.5.6
https://github.com/docker/machine/releases/download/v0.5.6/docker-machine_darwin-amd64

May we can get the filename from the github api?

**Comment by lordofthejars** [comment]
Well I will say that we always download the latest one which we are compatible.
