### ISSUE TITLE
InvalidPathException: UNC path is missing sharename: /\.dockerenv (Top.java) on Windows

### ISSUE THREAD

**Issue by foxlegend** [arquillian/arquillian-cube#308]
Hello there,

When upgrading to Cube 1.0.0.Alpha9, a new problem appeared on Windows.
Launching tests results in the attached stacktrace: [arquillian_cube_1.0.0.Alpha9_stacktrace.txt](https://github.com/arquillian/arquillian-cube/files/156807/arquillian_cube_1.0.0.Alpha9_stacktrace.txt)

Thus, when trying to debug the problem, I found that it was a problem of path interpretation using the java.nio API. As on Linux systems `/something` represents a file at the root directory, on Windows it looks for a hostname resulting in the stacktrace.

So I shadowed the `Top` class and replaced the usage of java.nio paths by simple `Files` and everything seems working normally now.

I did not found other workaround regarding paths interpretation with java.nio for now…

**Comment by lordofthejars** [comment]
First of all thank you very much for using Cube and sorry for any inconvenience it is causing you. Yes it seems the problem is with the added of DinD support.  Can you provide a PR?  We are going to release a new version next week so this fix could be inside.

Alex.

**Comment by foxlegend** [comment]
No need to apologize ;) I'll provide a PR as soon as possible !

David.
