### ISSUE TITLE
certificate validation fails when not using boot2docker nor docker machine

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#324]
@lordofthejars @aslakknutsen 

In case I run natively on Linux, without boot2docker nor docker machine, there is this exception:

This is the cause:

```
    com.github.dockerjava.api.exception.DockerClientException:
Certificate path (DOCKER_CERT_PATH)
'/home/smikloso/.boot2docker/certs/boot2docker-vm' doesn't exist.
        at com.github.dockerjava.core.DockerClientConfig.checkDockerCertPath(DockerClientConfig.java:112)
        at com.github.dockerjava.core.DockerClientConfig.<init>(DockerClientConfig.java:85)
        at com.github.dockerjava.core.DockerClientConfig$DockerClientConfigBuilder.build(DockerClientConfig.java:432)
        at org.arquillian.cube.docker.impl.docker.DockerClientExecutor.<init>(DockerClientExecutor.java:161)
        at org.arquillian.cube.docker.impl.client.DockerClientCreator.createClient(DockerClientCreator.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

DockerClientConfig from docker-java fails on this because if it is not null and if tls verify thing is true, it will check the presence of that certificate but Cube resolved it bad because of the following so it fails as well:

https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java#L205-L207

https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java#L247-L253

I do not have machine set so it will use else branch. But I do not have boot2docker either.

We should be able to make the difference between three cases, docker machine, boot2docker and native. Currently there is fallback just to boot2docker in case it is not run on machine.

**Comment by lordofthejars** [comment]
agreed. What I don't understand is why it has not failed until now.

**Comment by smiklosovic** [comment]
So, Alex did this:

https://github.com/lordofthejars/arquillian-cube/commit/b6042ed0a2a0f3d80c4998f1780f46e12f17b477

I have changed tcp scheme to "unix" but it fails on this:

```
    com.github.dockerjava.api.exception.DockerClientException: Certificate path (DOCKER_CERT_PATH) '/home/smikloso/.docker/certs' doesn't exist.
        at com.github.dockerjava.core.DockerClientConfig.checkDockerCertPath(DockerClientConfig.java:112)
        at com.github.dockerjava.core.DockerClientConfig.<init>(DockerClientConfig.java:85)
        at com.github.dockerjava.core.DockerClientConfig$DockerClientConfigBuilder.build(DockerClientConfig.java:432)
        at org.arquillian.cube.docker.impl.docker.DockerClientExecutor.<init>(DockerClientExecutor.java:163)
```

I think that you are still coping with docker machine, that .docker/certs path is used in docker-machine itself. 

http://stackoverflow.com/questions/31176262/what-does-the-docker-tls-verify-and-docker-cert-path-variable-do

**Comment by smiklosovic** [comment]
So the situation is like this:

when I do not set that dockerCertPath, it will build that configuration here 

https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java#L157-L161

and it will be built here:

https://github.com/docker-java/docker-java/blob/7c27d149876c19bb233f7dc865bee163a0aa601e/src/main/java/com/github/dockerjava/core/DockerClientConfig.java#L431-L434

So it will check the existence of that certificate here

https://github.com/docker-java/docker-java/blob/7c27d149876c19bb233f7dc865bee163a0aa601e/src/main/java/com/github/dockerjava/core/DockerClientConfig.java#L103-L126

But that is checked only in case that dockerTlsVerify is true so if it is false, it will not check it so it should return null.

So I would have to set that tls verify to false in order not to check it.

Then when you are dealing with building of client executor, it is done like this:

https://github.com/docker-java/docker-java/blob/7c27d149876c19bb233f7dc865bee163a0aa601e/src/main/java/com/github/dockerjava/jaxrs/DockerCmdExecFactoryImpl.java#L162-L187

In my case, when tlsVerify is false, protocol will be "http". Next, I do have "tcp" as my scheme so when it does not equal "unix", it will effectively replace "tcp" with "http".

I have to find a way how to turn of that tls verification, that could do something.

**Comment by smiklosovic** [comment]
https://github.com/arquillian/arquillian-cube/pull/325
