### ISSUE TITLE
Docker machine is started automatically even I want to use native containers

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#337]
It took me a while to spot this but I am using arquillian.xml in both host and machine mode and in case I want to start containers natively without machine, Docker Machine is started anyway - even it is not used as a runtime for containers.

I briefly checked the sources and it seems to me that the code which starts the machine is this (1)

I do have "machineName" in arquillian.xml but my serverUri points to local Docker daemon. I do have just one Docker Machine and I do have docker machine binary installed so this all mean that, accidentally, Docker machine is started even I do not want it.

(1) https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java#L135-L145

**Comment by smiklosovic** [comment]
I remember that it was possible to have "machineName" in arq.xml and it would not start it if I run containers in native mode. Maybe autostarting of Docker machine should be "false" by default or in case you are running against local docker it would not be started in case it is turned off.

**Comment by lordofthejars** [comment]
Yes this is the default behaviour for now, and probably is wrongly now that MacOS can also start Docker natively. I am not sure what could be the best option here. It is true that it seems reasonable that if user has configured machine name it means he wants to use docker machine. Any thoughts on this @aslakknutsen and @bartoszmajsak ?

**Comment by smiklosovic** [comment]
@lordofthejars right ... but if it is done in such way that when machineName is set it starts it, even I do not want it, it will automatically prevent me from using one arquillian.xml for both scenarios just because of one property.

**Comment by lordofthejars** [comment]
@smiklosovic do you know any way to detect if docker CLI is pointing to docker machine or not? I understand your point but if machineName is set then you are tight to docker machine.

**Comment by smiklosovic** [comment]
when serverUri has string "dockerMachine" or something similar in it, dont you assume it will be automatically replaced by ip of machine? hence if that string is not there, would not you assume that you do not run machine hence you do not start it?

**Comment by smiklosovic** [comment]
if it is done in such way that you start machine and after it is started you replace that string by its ip, it is useless. however if you start machine iff that string is going to be expanded, that could be something

**Comment by lordofthejars** [comment]
right, well serverUri is not expandable if you are running in linux, the problem is that if you set dockerMachine and you are under linux maybe you still want to use docker machine in Linux. Since you can overwrite arquillian properties using system properties, I recommend that in these cases just unset machineName.

**Comment by smiklosovic** [comment]
thats nice advice
