### ISSUE TITLE
Add support for depends_on

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#352]
Need to add support for `depends_on` in docker compose (and cube format) which means adding an ordered way to start containers. Obviously this means changing some of the AutomaticAutoStart resolutions to not only take into consideration links (in case of no network) and just use `depends_on` in case of network.

**Comment by eddumelendez** [comment]
@lordofthejars I think that this should be closed.

**Comment by lordofthejars** [comment]
True, thanks.
