### ISSUE TITLE
If not docker-machine name defined an exception is thrown

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#370]
If not docker-machine name defined an exception is thrown but docker-machine is running it should take this instance as machine, but in this case it tries to run boot2docker.

**Comment by eddumelendez** [comment]
@lordofthejars I have tested commenting the following line

```xml
<property name="machineName">dev</property>
```

and everything is ok. The only problem I had was when I use empty `machineName`:

```xml
<property name="machineName"></property>
```

**Comment by lordofthejars** [comment]
I tried with not setting it in MacOS and it crashed. Did you tried in Mac?

**Comment by eddumelendez** [comment]
Yes, I tested it in mac. I was also reviewing all the code and looks good to me but sometimes looks like `docker-machine` is not detected, pretty weird. Today, everything ran ok. I will keep testing.

**Comment by lordofthejars** [comment]
Look take the ftest containerless example. This was the example where I
detected

**Comment by lordofthejars** [comment]
No worries I have found the problem. I had two docker machines started, one locally and another one for digital ocean account. So everything is fine.
