### ISSUE TITLE
downloading of docker-machine fails

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-cube#373]
I do not have ~/.arquillian and spacelift fails to download a docker-machine.

I was thinking that it will automatically create whole path but I have to explicitly create `/home/smikloso/.arquillian/machine/v0.7.0/docker-machine` in order to have it passed.

However, looking into `docker-machine` directory, it is empty so it is not downloaded anyway.

**Comment by eddumelendez** [comment]
@smiklosovic thanks for the report. I have just submitted a PR to fix this issue.
