### ISSUE TITLE
Integration with Pact-JVM

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#386]
Integrating Cube to https://github.com/DiUS/pact-jvm so basically the user sets the container (AS) where client is going to be executed (this is nothing new since it is the same way as it is been doing now) but since it is executed in a Docker container we need to copy the result file to host.

Then user need to explicitly say which is the producer container and Cube will execute the other part of the tests.

**Comment by lordofthejars** [comment]
It has not much sense for now implementing this integration since consumers won't use docker and providers needs the docker host ip which is already provided by cube.

**Comment by bbarke** [comment]
I think this would be a great addition to arquillian. Why won't consumers use Docker? In my case, the consumer is developed inside of a docker container where a complex configuration is already setup. Duplicating that setup/configuration for the JEE container just to shrink wrap a few classes has proven to be very difficult.

**Comment by lordofthejars** [comment]
Cannot see exactly the use case. I mean Pact Stub Http server runs automatically you don't need any docker image. Then your consumer can be dockerized but the test needs to be fired.

So I suppose that what you mean is dealing with ShrinkWrap thing so everything is packaged automatically, which I think it is already done with Arquillian Algeron automatically : https://github.com/arquillian/arquillian-algeron/tree/master/pact/consumer/ftest-container http://arquillian.org/arquillian-algeron/
