### ISSUE TITLE
Allow parallel execution of tests

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#392]
It is perfectly fine to execute in same docker host same containers to run different tests against them.

For this reason we need to indicate to container name that there is a part of the name that should be dynamically generated.

For example given:

```
tomcat:
  image: tutum/tomcat
```

implies that container instance is going to be called `tomcat` and this means that test cannot run in parallel in the same docker host since it will throw a conflict.

So it will be interesting do something like:

```
tomcat*:
  image: tutum/tomcat
```

The `*` indicates that before starting everything, the definition will be redefined to something like:

```
tomcat1:
  image: ....
```

Of course things get worst when you have links since you need to duplicate everything and set as environment variable the new DNS but it can be done without much problem.

Then if you do this and you run from IDE, nothing is going to happen, you will still have only one container, but if you run in `Gradle` or `Maven` and you run tests in parallel, you will see different instances of same container in Dockerhost.

Of course you could even replicate the business container and share the persistence container acorss all the instances.

**Comment by bartoszmajsak** [comment]
One thing to keep in mind is to deal with port offsets somehow in a smart way, as external ports have to be unique.

**Comment by pwoelfle** [comment]
In which way it is possible to inject the host port or url to the Arquillian test?
I have tried following, but `hostPort` and `containerUrl` return `0` and `null`:
```
@HostPort(containerName = "tomcat*", value = 8080)
int hostPort

@DockerUrl(containerName = "tomcat*", exposedPort = 8080)
@ArquillianResource
URL containerUrl
```
Did I missed something?

I think the problem is the equals-check in `org.arquillian.cube.impl.model.LocalCubeRegistry#getCube(java.lang.String)`. A simple solution could be something like:

```
    @Override
    public Cube<?> getCube(String cubeId) {
        for(Cube<?> cube : this.cubes) {
            if(isMatchingCubeId(cube.getId(), cubeId))) {
                return cube;
            }
        }
        return null;
    }

    private boolean isMatchingCubeId(String cubeId, String requestedCubeId){
        if(requestedCubeId.endsWith("*")){
            String starlessRequestedCubeId = requestedCubeId.substring(0, requestedCubeId.length() - 1);
            return cubeId.startsWith(starlessRequestedCubeId);
        }

        return cubeId.equals(requestedCubeId);
    }
```

A better solution in my opinion could be introducing a proper interface for the `CubeId` with two implementations `DefaultCubeId` and `StarredCubeId`. This would cause some refactoring. 

What do you think?

**Comment by lordofthejars** [comment]
You are totally right, you can contribute with PR or if you cannot, I am
going to work with a fix next week

Thank you very much for your help on improving Cube

Alex

El 17 feb. 2017 8:03 p. m., "Pascal Wölfle" <notifications@github.com>
escribió:

In which way it is possible to inject the host port or url to the
Arquillian test?
I have tried following, but hostPort and containerUrl return 0 and null:

@HostPort(containerName = "tomcat*", value = 8080)
int hostPort

@DockerUrl(containerName = "tomcat*", exposedPort = 8080)
@ArquillianResource
URL containerUrl

Did I missed something?

I think the problem is the equals-check in org.arquillian.cube.impl.
model.LocalCubeRegistry#getCube(java.lang.String). A simple solution could
be something like:

    @Override
    public Cube<?> getCube(String cubeId) {
        for(Cube<?> cube : this.cubes) {
            if(isMatchingCubeId(cube.getId(), cubeId))) {
                return cube;
            }
        }
        return null;
    }

    private boolean isMatchingCubeId(String cubeId, String requestedCubeId){
        if(requestedCubeId.endsWith("*")){
            String starlessRequestedCubeId =
requestedCubeId.substring(0, requestedCubeId.length() - 1);
            return cubeId.startsWith(starlessRequestedCubeId);
        }

        return cubeId.equals(requestedCubeId);
    }

A better solution in my opinion could be introducing a proper interface for
the CubeId with two implementations DefaultCubeId and StarredCubeId. This
would cause some refactoring.

What do you think?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/arquillian/arquillian-cube/issues/392#issuecomment-280737540>,
or mute the thread

**Comment by pwoelfle** [comment]
Thank you Alex for your fast answer. I will create a PR in the next days.

**Comment by pwoelfle** [comment]
@lordofthejars PR created: https://github.com/arquillian/arquillian-cube/pull/586
