### ISSUE TITLE
Can't build the master

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#399]
I tried to build the master and hit all kinds of issues, so apparently I miss something.

1. Tried with JDK 1.7.0_79 and I am hitting `is missing value for the attribute <clinit>`.
2. Tried with JDK 1.8.0_91 and I am having test failures:

<details>
  <summary>Failed tests</summary>
````
 CubeConfiguratorTest.dockerUriConfigurationParameterShouldTakePrecedenceOverSystemEnv:413 
Expected: map containing [is "certPath"->a string ending with ".boot2docker/certs/boot2docker-vm"]
     but: map was [<serverUri=tcp://192.168.0.1:22222>, <dockerServerIp=192.168.0.1>, <tlsVerify=false>]
  CubeConfiguratorTest.shouldUseBoot2DockerIfDockerHostIsSetOnServerURIByDefault:109 
Expected: map containing [is "certPath"->a string ending with ".boot2docker/certs/boot2docker-vm"]
     but: map was [<serverUri=tcp://192.168.0.1:22222>, <dockerServerIp=192.168.0.1>, <tlsVerify=false>]
  CubeConfiguratorTest.tlsVerifyShouldBeTrueInCaseOfCertPathPresent:333 
Expected: map containing ["tlsVerify"->"true"]
     but: map was [<serverUri=tcp://192.168.0.2:22222>, <dockerServerIp=192.168.0.2>, <tlsVerify=false>]
  CubeConfiguratorTest.tlsVerifyShouldBeTrueInCaseOfNotSetAndDockerHostTagNotPresent:271 
Expected: map containing ["tlsVerify"->"true"]
     but: map was [<serverUri=tcp://192.168.0.2:22222>, <dockerServerIp=192.168.0.2>, <tlsVerify=false>]
  CubeConfiguratorTest.tlsVerifyShouldBeTrueInCaseOfNotSetAndDockerHostTagPresent:317 
Expected: map containing ["tlsVerify"->"true"]
     but: map was [<serverUri=tcp://192.168.0.2:22222>, <dockerServerIp=192.168.0.2>, <tlsVerify=false>]
````
</details>
<details>
  <summary>Tests in error</summary>
````
  AwaitStrategyTest.should_be_able_to_use_wait_for_it_await_strategy:41 » Execution
````
</details>

In both cases tried with maven  3.3.9 

Some of the failures give me the impression that certain env variables or system properties are expected to be found. Now, I would expect that these are either set by surefire or documented?

EDIT: With a closer look it seems that most of my problems come from the fact that the value of tlsVerify is false. This is also the root cause why the `certPath` is not present. FWIW I am on linux.

**Comment by lordofthejars** [comment]
It is strange because you are not the only one who has found this problem. I am not sure why this is happens since everything is mocked.

**Comment by bartoszmajsak** [comment]
I can only confirm it's the same problem for me. I would assume not all mocks are wired properly together?

**Comment by iocanel** [comment]
@lordofthejars: There is something missing here (or I am missing something obvious).

Take `tlsVerifyShouldBeTrueInCaseOfNotSetAndDockerHostTagPresent` for example:

- docker uri is provided explicitly
- tls is not set

so its expected that tlsVerify = true but I do get tlsVerify=false, why?

according to https://github.com/arquillian/arquillian-cube/blob/2889021b9ef893da32f7f9e6bd577dda0b489625/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java#L346 if you are on linux and docker machine is not set, then tlsVerify shoud be false. Now, I am on Linux and the test case doesn't mock something related to docker machines (or at least this is my understanding).

**Comment by iocanel** [comment]
Commenting out this line: https://github.com/arquillian/arquillian-cube/blob/2889021b9ef893da32f7f9e6bd577dda0b489625/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java#L356

Fixes all the tls related failures and I am left with only one error.

**Comment by lordofthejars** [comment]
Well the solution should not be comment this line, probably we need to mock the operative system too

**Comment by lordofthejars** [comment]
I think the solution is adding an `assumeThat` since in Linux the test should be false not true

**Comment by lordofthejars** [comment]
The problem is that I cannot test since I am in Mac. So what I would do is something like:

`Assume.assumeThat(new OperatingSystemResolver().currentOperatingSystem().getFamily(), is(not(OperatingSystemFamily.LINUX)));`

**Comment by bartoszmajsak** [comment]
> The problem is that I cannot test since I am in Mac. 

How about VM with Linux on it? ;)

**Comment by lordofthejars** [comment]
Yes but it is faster if you can do the assumeThat than me having to install everything (VM, Linux, Maven, git, ....)

**Comment by lordofthejars** [comment]
@iocanel If you want I send a PR with all the `assumeThat` calls.

**Comment by iocanel** [comment]
@lordofthejars: let me try it here first and I'll share my experience.

**Comment by iocanel** [comment]
works great!  so feel free to send a pr!

**Comment by lordofthejars** [comment]
You tried what I suggested in all failing tests right?

**Comment by iocanel** [comment]
Yes! It fixes all failing tests and we are now left to deal with the error, which I think I can tackle.

**Comment by lordofthejars** [comment]
Currently master has the

**Comment by iocanel** [comment]
Now the NodeTest is failing me!

Is there a ci env somewhere that periodically tests master, or tests pull requests against? It would definitely help here.

**Comment by lordofthejars** [comment]
We should do something, the problem is that only docker main tests can be
run, since ftests requires a lot of environment configuration

El dt., 19 jul. 2016 a les 14:57, Ioannis Canellos (<
notifications@github.com>) va escriure:

**Comment by lordofthejars** [comment]
Some ftests requires docker machine, others boot2docker and others native docker. In case of NodeTest it only runs if  you are using a docker-machine. I know we should improve this in CI or maybe just add assumeThat in every test

**Comment by iocanel** [comment]
We had similar issues, with fabric8 too.

The approach we took in the end is to move anything that has external dependencies (docker, kubernetes, openshift) to separate modules and separate profiles. Personally, I don't fancy that approach because moving tests in a different module pretty much guarantees that they will become stale.

I think I like the assumeThat approach better, but still feel there is a gap we need to feel....

I am pretty sure that this is going to be a problem that will taunt our users themselves and I am wondering if we should build something to handle that for them. For example I would prefer if instead of assumeThat I had a couple of annotations: @OnDocker, @OnBoot2Docker,  @OnDockerMachine(name="dev"), @OnKubernetes, @OnOpenshift and so on. If the condition is not meet the test can be completely ignored (not even run).

**Comment by lordofthejars** [comment]
In fact in Cube we are almost there, I mean what we do is if you are on Windows or Mac we search for a docker machine or boot2docker installation. If you are in Linux and if you set machineName means that you are using docker machine in Linux and if not we use automatically native docker.

Also not setting machineName means that Cube tries to resolve docker machine and if not then it is a native docker.

So it seems that we have some gaps but we are trying to do as automatic as possible.

But it is true that adding some kind of annotations might help.

**Comment by iocanel** [comment]
This is more complex than I thought and neither assumeThat nor some annotations on the test itself can be much of a help, as its not the test that fails but deployment.

Is there a way to do something equivalent to assume with the deployment? The only thing that comes to my mind is playing with Rule (but I am not even sure if that would work).

**Comment by aslakknutsen** [comment]
Perhaps Arquillian Governor could help here?

Maybe one of the existing extensions like Ignore or Skipper, or a custom impl for some Cube specific tasks. 
https://github.com/arquillian/arquillian-governor

It won't help for stuff that starts up in Application/Suite scope tho...

**Comment by iocanel** [comment]
If the arquillian test spi provided an execution decider for test suites and classes (which seems feasible), then we could possibly have skipper or something like it, used with a wider scope.

Of course, even if feasible, this would require a release or two....

**Comment by iocanel** [comment]
@aslakknutsen, @lordofthejars:  I had success with implementing junit rules and annotations. This is not the ideal solution, but its a viable one that doesn't require releasing additional projects (arquillian spi, skipper etc).

If you are interested I can contribute them back to the project either as an internal solution (just to get our tests going) or as something that our users can use for their own tests.

**Comment by bartoszmajsak** [comment]
I would say let's bring it in and create a task for `governor` to cover this functionality. I think for the time being important is to bring those two projects together and then we can polish it (maybe even before releasing new version of Cube).

Thanks a lot for all your work so far!

**Comment by iocanel** [comment]
As, I am moving forward I am hitting cases that are not covered by this solution :-(

**Comment by lordofthejars** [comment]
mmm I think `governor` should be the solution at long-term.

**Comment by iocanel** [comment]
Totally agree!

**Comment by iocanel** [comment]
I created a new issue which clearly describe the actions required and I have a pull request to send soon. I think that we can close this one. The new issue is #400.
