### ISSUE TITLE
Provide a mechanism for tests/suites to run if certain assumptions are satisfied.

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#400]
Currently all tests are run regardless if the target environment provides everything it needs for tests to run. Examples of such requirements are:

- docker
- boot2docker
- docker machine
- system properties
- env variables

The issue can be partially addressed using junit's Assume.assumeThat(...), but unfortunately it doesn't solve all issues. Some of the issues that it can't tackle are issues that happen before the execution of the tests method. Such cases are:

- placeholder substitution.
- errors happening at the application or suite level.

We need of way that can handle this. A long term solution could be governor, but even governor can't handle those at the moment.

So as short term solution we need:

- a declarative way to express those requirements
- a runner and/or junit rule we can use to handle those requirements/assumptions.

**Comment by lordofthejars** [comment]
I leave open until docs are provided, so you can link to the same issue.

**Comment by lordofthejars** [comment]
I have created the docs so I close this.
