### ISSUE TITLE
OpenShift port-forwarding does not support overriding the local port value

### ISSUE THREAD

**Issue by rcernich** [arquillian/arquillian-cube#440]
You either get a random port or the same as the target port.

We're trying to run upstream integration tests (e.g. JDG) on a productized image (e.g. jboss-datagrid-6/datagrid65-openshift) and need to be able to specify the local ports as we can't change the tests themselves.

**Comment by jwendell** [comment]
isn't this fixed by #441 ?

**Comment by lordofthejars** [comment]
it seems so, so we can close it right?

**Comment by jwendell** [comment]
I think so, yes.
