### ISSUE TITLE
ArquillianKubeResourceProvider should also work with javax.inject.Named

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#442]
Currently, they require a custom annotation `org.arquillian.cube.kubernetes.annotations.Named`.
Users that read examples easily confuse that with `javax.inject.Named`. 

I think that both should be supported, to make the life of users easier.

**Comment by lordofthejars** [comment]
This is something that we usually don't use in Arquillian extensions, but if you think it has sense we could provide support for both.

Maybe what we could do is add in `@ArquillianResource` an attribute named `name` to inject an specific resource.What do you think @bartoszmajsak @aslakknutsen

**Comment by iocanel** [comment]
Just to clarify what I am proposing is to use reflection instead and support any kind of Named annotation without being coupled to any. 

It's just a safety net for the users. FWIW, I think that guice uses the exact same approach too.
