### ISSUE TITLE
GitServer in arquillian-cube-openshift is using hostPort

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#447]
Using a hostPort is not considered a good practice and in many environments its not even allowed. In other cases it requires messing up with `security context constraints` and may lead to hard to troubleshoot issues.

For example I was getting a similar exception to #444, and it took me a lot of trial an error, before I manage to understand what is going on.

**Comment by iocanel** [comment]
I think that instead of hostPort we should use a Service.

**Comment by lordofthejars** [comment]
In this case you are talking about cube-openshift extension and not the kubernetes one.

@jwendell and @spolti might help you on this since they are doing an awesome work in that part.

**Comment by spolti** [comment]
Hi, I 'll be glad to help but I am afraid I didn't understand exactly what is the issue that you described or are facing. Could you please add more details on your issue/question and what is your use case?

**Comment by iocanel** [comment]
The code here: https://github.com/arquillian/arquillian-cube/blob/master/openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/client/GitServer.java#L91 defines a hostPort on the pod. 

This is something that is generally considered a bad practice (see [1]). Also its something that is not supported on all environments (e.g. Openshift dedicated). But even with plain Openshift, it requires certain configuration on the user side in order for that to work (more specifically it requires that the user is associated with a security context constraint that allows host ports). 

So what I am suggesting, is to remove the hostPort definition from the pod and use a service instead. So that we access the git server through the service. Ideally we should also expose the service as a route (if possible) so that its easier to consume externally.

[1]:http://kubernetes.io/docs/user-guide/config-best-practices

**Comment by spolti** [comment]
Looks like it is a fabric8 implementation (io.fabric8.kubernetes.api.model.PodBuilder),
I did look quickly at cube-kubernetes to now if the git server is implemented there but looks like it is not the case.

I guess it can't be changed directly on arquillian-cube without the proper change on fabric8.

@aslakknutsen, @lordofthejars  any idea?

**Comment by iocanel** [comment]
The PodBuilder doesn't need to change. I am just suggesting that that the GitServer class should not use the `withHostPort()` method.

Maybe it would be simpler if I provided a PR and we could continue the discussion on the PR.

**Comment by lordofthejars** [comment]
@spolti notice that @iocanel is talking about openshift module and not kubernetes module.
