### ISSUE TITLE
Creates an AssertJ custom assertions

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#461]
Creates an AssertJ custom assertions for reading attributes so you can do things like:

```
@ArquillianResource
DockerClient docker;

assertThat(docker).hasImage("myimage");
assertThat(docker).runningContainers().filter("myimage", "myimage2");

assertThat(docker).container("myinstancename").hasProcessRunning("myprocess")
assertThat(docker).container("myinstancename").hasExposedPorts(8080);
assertThat(docker).container("myinstancename").hasBindPorts(8080);

assertThat(docker).container("myinstancename").hasFile("/tmp/log");
assertThat(docker).container("myisntancename").logs().doesNotContainText("Exception", "Error");

```

You can read more about custom assertions at http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html

**Comment by bartoszmajsak** [comment]
> assertThat(docker).runningImages().filter("myimage", "myimage2");

what does it suppose to test?

**Comment by lordofthejars** [comment]
the name is wrong should be `runningContainers` and checks that these containers are running in the given docker host

**Comment by bartoszmajsak** [comment]
But then filter is misleading I guess.

**Comment by lordofthejars** [comment]
well you can do something like `myimage*`

**Comment by lordofthejars** [comment]
@iocanel @jwendell What are your thoughts about this issue?

**Comment by bartoszmajsak** [comment]
@lordofthejars I mean it does not say what is asserted really in this given case.

**Comment by lordofthejars** [comment]
Then we can do: .containers().filter("..", "..").areRunning()

**Comment by iocanel** [comment]
For the kubernetes bits, we already have something like this in fabric8 (https://github.com/fabric8io/fabric8/tree/master/components/kubernetes-assertions), so the question really is, does it make sense to also migrate this or not.

Most of the job on this has been done by @jstrachan. So @jstrachan wdyt?

**Comment by jstrachan** [comment]
I don't really see why we need to move it. I tend to continue to improve the assertions over time as it gets used by fabfic8.

Kubernetes-assertions are also quite independent of the use of Arquillian. If anything I'd rather it was in the kubernetes-client project

**Comment by jstrachan** [comment]
Note also that kubernetes-assertions lets you perform deep assertions on any part of the kubernetes or openshift models via a single line of code - very handy for testing - but also something that is better tied to kubernetes-model & client releases to keep them all in sync

**Comment by lordofthejars** [comment]
Yes I think we can leave that bits there, I just asking to create the same for docker here.

**Comment by eddumelendez** [comment]
I really like this idea... but what if it is a independent project built on top of `docker-java` instead of depends on arquillian?

**Comment by bartoszmajsak** [comment]
I think we can keep it under the org, but have nothing related to Arq as such.

**Comment by eddumelendez** [comment]
Hi guys, I have a prototype [assertj-docker-java](https://github.com/eddumelendez/assertj-docker-java)
