### ISSUE TITLE
Openshift: Resolve routes

### ISSUE THREAD

**Issue by jwendell** [arquillian/arquillian-cube#465]
Two things here:
- Ability to inject a route in a test based on its name on the Openshift cluster:

``` java
    @RouteURL("eap-app")
    private URL url;
```

 The `url` variable above would contain something like 'http://url-of-the-openshift-router', assuming there's a router with the name `eap-app` there.
 Our team has an working implementation of this: https://github.com/jboss-openshift/ce-arq/blob/master/cube/src/main/java/org/jboss/arquillian/ce/cube/enrichers/RouteURLEnricher.java
- Ability to resolve non-public addresses. This is the case when your route is not resolvable. For instance, the default dns name for an openshift service is something like `eap-app.router.default.svc.cluster.local`. This is clearly not resolvable. So, in order to reach this endpoint from the client side, we need to workaround this dns thing. One can edit `/etc/hosts` file adding this dns name and its corresponding IP address, but this is not scalable.
  In our team we added a dns resolver layer into cube: https://github.com/jboss-openshift/ce-arq/tree/master/cube/src/main/java/org/jboss/arquillian/ce/cube/dns

So, perhaps makes sense to move those implementations from our downstream project to the upstream project so that others can benefit.

**Comment by bartoszmajsak** [comment]
If the goal is to have prime support for Openshift testing in Cube I think this is very valuable contribution. Thanks for suggesting it!

@lordofthejars I guess we can take care of it within our own team? Should be easy enough,

**Comment by bartoszmajsak** [comment]
Is there anything else not so specific for `ce-arq` module which we could think of moving up? If so, feel free to fire another issues.

**Comment by lordofthejars** [comment]
@jwendell I will move these pieces today. Of course if you think anything else can be moved from CE to Cube please don't hesitate to share with us

**Comment by bartoszmajsak** [comment]
Thanks, we will take it over.

**Comment by spolti** [comment]
Partially fixed by https://github.com/arquillian/arquillian-cube/pull/776
I'll also be porting the dns service to arquillian-cube soon.

**Comment by spolti** [comment]
@lordofthejars I believe our implementation have a different purpose.
We add dns entries in the jvm's name service with the openshift router ip and the route to the app and make it resolvable for tests annotated with @RunAsClient.

**Comment by lordofthejars** [comment]
Ah nice, then I wait for the PR. Also it would be good to document your use case and @iocanel use case clearly so users don't get confused.

**Comment by Ladicek** [comment]
IMHO, this can be closed.
