### ISSUE TITLE
Openshift: Instantiate templates

### ISSUE THREAD

**Issue by jwendell** [arquillian/arquillian-cube#467]
[Templates](https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/templates.html) are a useful resource in Openshift, and it would be great if cube supported it out of the box.

In the [ce-arq](https://github.com/jboss-openshift/ce-arq) project we have created an [@Template](https://github.com/jboss-openshift/ce-arq/blob/master/api/src/main/java/org/jboss/arquillian/ce/api/Template.java) annotation that is responsible for instantiate (i.e., create all resources defined within a template) before the test execution.

An example of usage can be seen in our [ce-testsuite project](https://github.com/jboss-openshift/ce-testsuite/blob/master/eap/eap70/src/test/java/org/jboss/test/arquillian/ce/eap70/Eap70ClusteringTest.java). Notice that this @Template mechanism also does variable substitutions (templates can contain variables, or [parameters](https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/templates.html#parameters)).

The way we implemented it can be seen [here](https://github.com/jboss-openshift/ce-arq/blob/master/cube/src/main/java/org/jboss/arquillian/ce/cube/CEEnvironmentProcessor.java#L148).

So, perhaps makes sense to move this thing from downstream ce-arq to upstream arquillian-cube.

**Comment by bartoszmajsak** [comment]
Thanks, we will take it over

**Comment by jwendell** [comment]
I'm willing to help here, spent some time understanding the internals of arquillian, arquillian-cube and cube-[k8s,openshift].

Before getting my hands dirty... do you have an opinion on how this could be implemented or you're happy with our approach of having an `@Template` annotation put before each test class?

**Comment by bartoszmajsak** [comment]
That's cool, I didn't know if you can get involved and you have time. But if you are willing to that's more than awesome :)

I think we start with `@Template` on the class level. I'm not sure if having any other convention here would be useful from the end-user perspective. I believe what you have came up with is providing you good experience and fulfills the use case :)

**Comment by bartoszmajsak** [comment]
So if you are up to hack on I can assign it to you (if you cannot do it yourself)

**Comment by jwendell** [comment]
@bartoszmajsak It seems I can't assign myself, feel free to do it.

**Comment by lordofthejars** [comment]
@jwendell it seems this issue is becoming an important issue to have fixed. My question is do you have time to move this feature from arq-ce to cube? If not if you can give some guidelines we are going to work on this.

**Comment by jwendell** [comment]
I'd be glad to help here. Although I don't have much time, I'll use my spare time to do this. Starting work now.

**Comment by Ladicek** [comment]
Just wanted to highlight that this is more important that the stuff mentioned in https://github.com/arquillian/arquillian-cube/issues/814

**Comment by jwendell** [comment]
So, as I stated in #468 , I don't have much spare time as I thought, so, I'll let @lordofthejars take over this work from me. Here's the WIP, feel free to take it as a start point: https://github.com/jwendell/arquillian-cube/tree/wip-templates

Feel free to unassign me from this issue.
