### ISSUE TITLE
Openshift: Support the creation of generic resources from a file

### ISSUE THREAD

**Issue by jwendell** [arquillian/arquillian-cube#468]
In the [ce-arq](https://github.com/jboss-openshift/ce-arq) project we have an [@OpenShiftResource](https://github.com/jboss-openshift/ce-arq/blob/master/api/src/main/java/org/jboss/arquillian/ce/api/OpenShiftResource.java) annotation that reads a JSON file and create the resources specified in it before the test execution.
- [Example of such a resource file](https://github.com/jboss-openshift/application-templates/blob/master/secrets/eap-app-secret.json)
- [Example of usage in a test](https://github.com/jboss-openshift/ce-testsuite/blob/master/eap/eap64/src/test/java/org/jboss/test/arquillian/ce/eap64/Eap64HttpsTest.java)
- [Our implementation](https://github.com/jboss-openshift/ce-arq/blob/master/utils/src/main/java/org/jboss/arquillian/ce/resources/OpenShiftResourceFactory.java#L62)

Does it make sense to move this thing to arquillian-cube?

**Comment by bartoszmajsak** [comment]
Thanks, we will take it over

**Comment by Ladicek** [comment]
Just wanted to highlight that this is more important that the stuff mentioned in https://github.com/arquillian/arquillian-cube/issues/814

**Comment by lordofthejars** [comment]
@jwendell @Ladicek I am going to start working on this

**Comment by jwendell** [comment]
@lordofthejars I believe this and #467 are tied together in our implementation in ce-arq. I started doing this work, and I was moving both features from ce-arq into arq-cube, i.e., I was going to provide a single PR that fixes both issues.

However I don't have much spare time to do that, progress is slow. As you volunteered to do this work, I suggest you do the same as of me: Copy bits from ce-arq into arq-cube directly. I pushed my work so far, perhaps you can start from there: https://github.com/jwendell/arquillian-cube/tree/wip-templates

So, I'm holding my work on this and will let you provide the PR. I'm happy to test it when it's done. Feel free to ping me if you need any help with stuff from ce-arq (I'm jwendell at IRC).

Thanks.

**Comment by lordofthejars** [comment]
Great, yes I'll start collaborating on your repo. Can I fork right now?

**Comment by jwendell** [comment]
Sure.
