### ISSUE TITLE
Containerless need to specify the definitionFormat = CUBE

### ISSUE THREAD

**Issue by eddumelendez** [arquillian/arquillian-cube#474]
When `containerless` is used the `definitionFormat` property needs to specified to `CUBE`.

Currently, the current default value for definitionFormat is `COMPOSE` and it´s not specified in the test example: [containerless/src/test/resources/aquillian.xml](https://github.com/arquillian/arquillian-cube/blob/master/containerless/src/test/resources/arquillian.xml). Said that, when `mvn test` is executed tests run OK but when tests are executed independently from IDE, for instance, `NodeTest` display `COMPOSE` in logs and tests fails.

**Comment by eddumelendez** [comment]
@lordofthejars WDYT?

**Comment by lordofthejars** [comment]
It has sense but I had no time to review

**Comment by lordofthejars** [comment]
I fixed this so I close the issue. Thanks.
