### ISSUE TITLE
Setup a circleci build for arquillian-cube

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#487]
We should at least have an indication that a pull request doesn't break the build on a neutral machine.
Since tests now express their requirements using the requirement annotations that should be the case.

Setting up something like circleci is just a matter of a few clicks for someone that has admin permissions. I'd gladly do it myself but I don't have permissions :-)

**Comment by lordofthejars** [comment]
Easy,I have invited to Arquillian Cube organization, when you accept I will give you admin rights.

**Comment by iocanel** [comment]
@lordofthejars: I accepted!

**Comment by bartoszmajsak** [comment]
And I just approved CircleCI request. Thanks for helping us!

I think we should think about minimal group of tests we should and are able to run on this platform. Besides plain docker stuff any others?

**Comment by iocanel** [comment]
Thanks, it ready now! Pull request will be tested. Example: #488

**Comment by bartoszmajsak** [comment]
This fails with `ci/circleci — No test commands were found`

**Comment by lordofthejars** [comment]
I think it is working now, can we close this issue?
