### ISSUE TITLE
Running test using boot2docker gives "Could not create wildfly-docker"

### ISSUE THREAD

**Issue by arun-gupta** [arquillian/arquillian-cube#49]
Following up from #48 ...

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.javaee7.servlet.metadata.complete.SimpleServletTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Dec 10, 2014 8:58:13 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > GET http://192.168.59.103:2376/v1.15/_ping

Dec 10, 2014 8:58:13 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 2 * Sending client request on thread main
2 > POST http://192.168.59.103:2376/v1.15/containers/create?name=wildfly-docker
2 > Accept: application/json
2 > Content-Type: application/json
{"name":"wildfly-docker","Hostname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Dns":null,"Image":"arungupta/javaee7-samples-wildfly","Volumes":{},"VolumesFrom":[],"WorkingDir":"","DisableNetwork":false,"ExposedPorts":{"8080/tcp":{},"9990/tcp":{}}}

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.356 sec <<< FAILURE! - in org.javaee7.servlet.metadata.complete.SimpleServletTest
org.javaee7.servlet.metadata.complete.SimpleServletTest  Time elapsed: 1.355 sec  <<< ERROR!
org.arquillian.cube.spi.CubeControlException: Could not create wildfly-docker
	at org.arquillian.cube.spi.CubeControlException.failedCreate(CubeControlException.java:19)
	at org.arquillian.cube.impl.model.DockerCube.create(DockerCube.java:69)
	at org.arquillian.cube.impl.client.CubeLifecycleController.create(CubeLifecycleController.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by lordofthejars** [comment]
I am going to close this issue because some users has done some work in this direction and they found a workaround. Anyway we are still working on this.

Workaround: https://github.com/arquillian/arquillian-cube/issues/78

**Comment by arun-gupta** [comment]
Workaround should only reduce the bug's priority as opposed to closing it?

**Comment by lordofthejars** [comment]
Yes sorry, the issue that is fixing this problem is https://github.com/arquillian/arquillian-cube/issues/52 we understood this issue more like a question because issue #52 is more general in the sense that fixes the problem with boot2docker but also with remote docker servers.
