### ISSUE TITLE
Provide a new url ResourceProvider for Kubernetes and Openshift

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#494]
Users would just want to grab a url and connect to a service without having much hassle.

We need to implement a url `ResourceProvider` and on top of that build some extra features, like:
- port forwarding support
- ingress support
- route support

**Comment by iocanel** [comment]
I have a draft of that ready, but I need #483 to be in place so that I can then move the port forward bits to kubernetes.

**Comment by lordofthejars** [comment]
I think this is done in PR right? https://github.com/arquillian/arquillian-cube/pull/561

**Comment by lordofthejars** [comment]
@iocanel is this enricher provided both for K8s and OpenShift?

**Comment by iocanel** [comment]
Yes

**Comment by lordofthejars** [comment]
So I can close the issue right?

**Comment by lordofthejars** [comment]
Ok now that this is merged, do we have a path to merge fabric8 arquillian thing into this in a safe way and just maintain one project?

**Comment by iocanel** [comment]
I think that we pretty much need to merge new stuff and fixes that have gone in since October.

However, not all fixes are applicable since a lot of stuff have been fixed at the client level. We will have to selectively pick a project or two and migrate them.

**Comment by iocanel** [comment]
... and see where we stand.

**Comment by lordofthejars** [comment]
right. Thank you very much for effort in standardization this.

**Comment by lordofthejars** [comment]
Maybe the idea would be that fabric8 project depends on this project. Then there will be only one code base

**Comment by iocanel** [comment]
Interesting idea....
