### ISSUE TITLE
should_report_network_topology_of_docker_containers fails

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#498]
https://github.com/arquillian/arquillian-cube/blob/f8b0ac239314976bb5c84d88ff8dbc8888a823c2/docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java#L284

It seems that no behavior is defined for this test case.

**Comment by lordofthejars** [comment]
What you mean by no behaviour, there is some assertions that asserts that the information is correctly created.

**Comment by iocanel** [comment]
I mean that the mock doesn't seem to define any behavior for the inspect method, which is indirectly called (resulting in an NPE).

**Comment by lordofthejars** [comment]
No, we are using the object just for capturing the result inside. https://github.com/arquillian/arquillian-cube/blob/f8b0ac239314976bb5c84d88ff8dbc8888a823c2/docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java#L293

**Comment by iocanel** [comment]
Does the test work for you?

**Comment by dipak-pawar** [comment]
@iocanel test is not working. Let me check what's wrong with it.

**Comment by dipak-pawar** [comment]
Submitted [PR](https://github.com/arquillian/arquillian-cube/pull/501) for above issue. Thanks @iocanel

**Comment by iocanel** [comment]
You may have to use something like the `@RequiresDocker` annotation so that the test will not fail on environments where docker is not available (e.g. circleci).

**Comment by dipak-pawar** [comment]
@iocanel there is bug in test code. No need to mention @RequiresDocker annotation for this tests as  we are providing networkMode from dockerContainers [properties](https://github.com/arquillian/arquillian-cube/blob/master/docker/recorder/src/test/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironmentTest.java#L48), and you will never reach [this](https://github.com/arquillian/arquillian-cube/blob/master/docker/recorder/src/main/java/org/arquillian/cube/docker/impl/client/reporter/TakeDockerEnvironment.java#L223) scenario.

**Comment by lordofthejars** [comment]
@iocanel fixed and merged :)
