### ISSUE TITLE
Await polling strategy should not make assumptions about the container environment

### ISSUE THREAD

**Issue by jamesnetherton** [arquillian/arquillian-cube#499]
I've been experimenting with cube and WildFly. Many of the examples I found reference the 'polling' await strategy. I encountered some problems with this:

Neither `ss` or `ping` is guaranteed to be available in the running container. Indeed, in the official WildFly base image, `ss` is not installed.

When using the 'wait-for-it' option, cube copies the script into '/'. There's no guarantee that the running container user has access to this location. Also, the `chmod` that [applies execute permissions](https://github.com/arquillian/arquillian-cube/blob/308287ec56a091d473309f21dcd3dff9f6a4fdf5/docker/docker/src/main/java/org/arquillian/cube/docker/impl/await/PollingAwaitStrategy.java#L137) to the script, incorrectly assumes that the `WORKDIR` is '/', which is not the case with the WildFly image (or the majority of JBoss base images).

**Comment by lordofthejars** [comment]
Thanks for reporting this. It is curious that when you do an exec process it runs it from `/` and not from configured `WORKDIR`. Then the problem is what to do in this case. In theory all docker images will have `/tmp` directory, isn't it? Then it could be an option too.

**Comment by jamesnetherton** [comment]
Yes, I was also thinking that maybe `/tmp` would be a good alternate location to copy & run the script.
