### ISSUE TITLE
NPE at ContainerConfigurationController.remapContainer()

### ISSUE THREAD

**Issue by jwendell** [arquillian/arquillian-cube#517]
```
java.lang.NullPointerException	at org.arquillian.cube.impl.client.container.ContainerConfigurationController.remapContainer(ContainerConfigurationController.java:86)
```

This was introduced by commit 7b890fe535c625390bb8f716455c618c39c5e490.

**Comment by jwendell** [comment]
@spolti is taking a look at this.

**Comment by bartoszmajsak** [comment]
Awesome, thanks guys!

**Comment by spolti** [comment]
Looks like the issue is caused because the mappingForPort is never reached when there is a group of containers on arquillian.xml is used, sending the fix.
