### ISSUE TITLE
Docker uri with tcp:// scheme incorrectly forces tlsVerify on OS X

### ISSUE THREAD

**Issue by jamesnetherton** [arquillian/arquillian-cube#525]
##### Issue Overview

On OS X if the `tcp` `dockerUri` scheme is used, cube forces `tlsVerify = true` and sets a `certPath` property. I think the problem code is [here](https://github.com/arquillian/arquillian-cube/blob/24a35347eae45a622be133f4705c588dd0ee807a/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolver.java#L208-L252). `TLS_VERIFY` config property seems to be forced to true, then there's some logic for Linux to modify it. But, this will never get triggered on other operating systems.

##### Expected Behaviour

`tlsVerify` and `certPath` properties should only be set if required.

##### Current Behaviour

`tlsVerify` and `certPath` are set when they should not be.

##### Steps To Reproduce

Unit tests:

```java
public class CubeDockerConfigurationResolverTest {

    @Test
    public void shouldNotSetTlsVerifyForTcpSchemeOnOSX() {
        CubeDockerConfigurationResolver resolver = new CubeDockerConfigurationResolver(new Top(),
                new DockerMachine(null),
                new Boot2Docker(null),
                OperatingSystemFamily.MAC);

        Map<String, String> config = new HashMap<>();
        config.put(CubeDockerConfiguration.DOCKER_URI, "tcp://localhost:2376");

        Map<String, String> resolvedConfig = resolver.resolve(config);

        Assert.assertFalse(Boolean.valueOf(resolvedConfig.get(CubeDockerConfiguration.TLS_VERIFY)));
        Assert.assertNull(resolvedConfig.get(CubeDockerConfiguration.CERT_PATH));
    }

    @Test
    public void shouldNotSetTlsVerifyForTcpSchemeOnLinux() {
        CubeDockerConfigurationResolver resolver = new CubeDockerConfigurationResolver(new Top(),
                new DockerMachine(null),
                new Boot2Docker(null),
                OperatingSystemFamily.LINUX);

        Map<String, String> config = new HashMap<>();
        config.put(CubeDockerConfiguration.DOCKER_URI, "tcp://localhost:2376");

        Map<String, String> resolvedConfig = resolver.resolve(config);

        Assert.assertFalse(Boolean.valueOf(resolvedConfig.get(CubeDockerConfiguration.TLS_VERIFY)));
        Assert.assertNull(resolvedConfig.get(CubeDockerConfiguration.CERT_PATH));
    }
}
```

**Comment by jamesnetherton** [comment]
The simple workaround for this would be to explicitly set `tlsVerify=false` in the arq config. But it should work OOTB IMO.

**Comment by lordofthejars** [comment]
But if you use `tcp://localhost` it means that you are using native docker installation in MacOS? I said this because AFAIK `docker-java` does not support this mode yet.

**Comment by jamesnetherton** [comment]
Ah - localhost was a bad example. My colleague was hooking into a docker instance that was exposed from within a VM. So it was `tcp://vm-host-name:2375`.

**Comment by lordofthejars** [comment]
ah ok :) Right what I think it is happening in your case is that when scheme is `tcp` does not enter to the if to set it to false. https://github.com/arquillian/arquillian-cube/blob/24a35347eae45a622be133f4705c588dd0ee807a/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurationResolver.java#L213 So this if should contain tcp scheme as well. I will fix it. Thanks for sharing.
