### ISSUE TITLE
Support for unix Socket

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#56]
Currently Arquillian Cube uses TCP to communicate with Docker server, but Docker server can also run using unix sockets. Allow developers to use this mode instead of TCP. 

This issue is related with https://github.com/docker-java/docker-java/pull/85

**Comment by aslakknutsen** [comment]
depends on #70

**Comment by lordofthejars** [comment]
I have tested and it works with unix sockets after upgrading to docker-client 10.5.
