### ISSUE TITLE
Add AssertJ matcher for current running processes

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#572]
##### Issue Overview

Add AssertJ matcher for current running processes
Code of assertions is placed athttps://github.com/arquillian/arquillian-cube/tree/master/docker/assertj

##### Expected Behaviour

You can assert on current running processes doing `assertThat(docker).container("mycontainer").hasProcessRunning("name of process")`

**Comment by dipak-pawar** [comment]
@lordofthejars Just wondering what will be the use case of this assertion scenario?

Does this name imply only name of process OR it also includes PID?

**Comment by lordofthejars** [comment]
The idea is that user can validate its Dockerfile

**Comment by dipak-pawar** [comment]
could you please give me some example where you can give process name in dockerfile which start the process by same name inside container?

**Comment by lordofthejars** [comment]
well in Dockerfile you can do `CMD /usr/local/tomcat/catalina.sh start` then I want to validate that tomcat is really started. In this case it is pretty obvious but imagine that a container are running some daemon processes and you want to check that they are really working.

After that we should implement another assertion which is `canExecute` but this is another thing.

**Comment by dipak-pawar** [comment]
I think instead of checking process running by it's name, we should check port is exposed by running telnet or some other networking tools. 

I am not sure about process name & it's naming convention strategy. I have seen but I didn't find process name for any running process.

**Comment by lordofthejars** [comment]
exposed port is already checked in assertj. The process in case of Tomcat is for example `java` right?

**Comment by dipak-pawar** [comment]
sure. but it might be possible at the same time you will have two java process inside container. what about adding n with `withSize()` methos to it? Something like

`assertThat(docker).container("mycontainer").hasProcessRunning("name of process").withSize(2)`

**Comment by lordofthejars** [comment]
yes in theory this should not happen since one container should be one process. But yes maybe you are right about doing in that way.

**Comment by dipak-pawar** [comment]
nopes. theory is correct. I realize it later.

**Comment by lordofthejars** [comment]
:)

**Comment by dipak-pawar** [comment]
@lordofthejars above situation can be possible in the case of systemd. I mean if we are starting systemd  which is starting some other processes.
