### ISSUE TITLE
Create standalone Hello-world ftest-example for cube-openshift.

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-cube#608]

**Comment by lordofthejars** [comment]
@dipak-pawar since there is already an ftest using standalone, has it sense to create another one?

**Comment by dipak-pawar** [comment]
@lordofthejars we have it for kubernetes. not for openshift.

**Comment by lordofthejars** [comment]
Ah Right sorry, I mixed this with another story. Thanks for the clarification.

**Comment by bartoszmajsak** [comment]
Just wondering how we can set it up in the CI env to actually run such tests. Minishift?

**Comment by lordofthejars** [comment]
I think that this could be an option, the other one would be use openshift origin

**Comment by dipak-pawar** [comment]
@bartoszmajsak  minishift or `oc cluster up`
