### ISSUE TITLE
Prepare for 1.0.0.Alpha20

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#629]
We have a lot of good stuff in the last couple of days, so it may be a good time for a new alpha release?

**Comment by iocanel** [comment]
Ideally after #630 gets in :-)

**Comment by lordofthejars** [comment]
Sure, they are free

**Comment by lordofthejars** [comment]
Let me review tomorrow with @bartoszmajsak https://github.com/arquillian/arquillian-cube/pull/628 and then we release it.

**Comment by lordofthejars** [comment]
Done

**Comment by lordofthejars** [comment]
@iocanel With latest Misc PRs do you need to update something from documentation?

**Comment by iocanel** [comment]
Yes, there are new stuff that we need to document. Mostly, the ability to use shell scripts from setting up the test namespace. I'll get on it ASAP.

**Comment by lordofthejars** [comment]
Cool thank you, so when we have this we will be able to do the announcements with the what's new :D
