### ISSUE TITLE
[Arquillian Cube - OpenShift] Running IT tests within a temporary/separate project requires admin privileges

### ISSUE THREAD

**Issue by RadekKoubsky** [arquillian/arquillian-cube#631]
##### Issue Overview
Hello,
we are working on integration tests for [Obsidian Toaster Quickstarts](https://github.com/obsidian-toaster-quickstarts), we want to use Arquillian Cube, the OpenShift extension.

Arquillian Cube requires admin privileges when running IT tests in a temporary/separate OpenShift project (e.g. create a new temporary project, run IT tests against it, delete the project). Our target platform is OpenShift Online, thus, we cannot run IT tests with admin privileges.

Do you think this is feasible from your point of view?
Thanks.
##### Expected Behaviour
Possibility to run IT tests without admin privileges on OpenShift Online.
##### Current Behaviour
IT tests using a temporary/separate OpenShift project require admin privileges.

**Comment by lordofthejars** [comment]
I think that this is a must for creating a new project in OpenShift, so from our perspective we cannot do much about this. The only think you can do is reuse an existing project, but that's all.

**Comment by iocanel** [comment]
FWIW, it also works with just the self-provisioner role.

**Comment by RadekKoubsky** [comment]
There is another problem with OSO (Free), a user is allowed to have only one project, thus no additional project for IT tests. OSO Free has a lot of limitations, I agree with using an existing project option (so we did in the quickstarts).
