### ISSUE TITLE
[Arquillian Cube - OpenShift] An example of use of the OpenShift extension that creates a new project for an integration test

### ISSUE THREAD

**Issue by RadekKoubsky** [arquillian/arquillian-cube#633]
I am working on an integration test ([here is the code I use](https://github.com/RadekKoubsky/rest_springboot-tomcat/tree/arquillian-cube-integration-test-openshift)) that is executed in a separate project. I am using fabric8-maven-plugin (FMP) to deploy the infrastructure in OpenShift, the expected workflow is as follows:

1) mvn fabric8:resource + mvn fabric8:build
FMP creates required resources (openshift.yml) and runs a build (in project you are currently logged in via oc), after the build, FMP creates a my-project-is.yml file (image stream definition) that refers to the runtime image with app jar.

2) mvn verify
Runs the integration test that should create a separate project, look for my-project-is.yml and openshift.yml, and deploy the infrastructure. After that, run the integration tests (call an app endpoint etc.).

I have not been able to make this work (cannot tell the Arquillian OpenShift extension to look for all required files), to configure the [arquillian.xml file](https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-openshift/src/test/resources/arquillian.xml#L6) properly. Just a note, I suppose there is distinction between kubernetes extension and openshift extension in terms of configuration. I was able to do somethinf with the kubernetes extension, bud didn't work for the openshit extension.

Can you please provide any working configuration (if it is possible) for this requirement or how to. Many thanks.

**Comment by dipak-pawar** [comment]
Thank you for Reporting this @RadekKoubsky.

We have recently added change for overriding all properties of k8s extension using openshift extension.

We are about to release new version of arquillian-cube.

If you want to give a try install snapshot dependency of arquillian-cube with latest master & use it in your project. Please have a look into https://github.com/arquillian/arquillian-cube/tree/master/openshift/ftest-standalone for more details.

**Comment by RadekKoubsky** [comment]
There is another issue I ran into using the kubernetes extension (I didn't even get there with the openshift extension). When the integraion test creates its own project in OpenShift, it seems like Arquillian Cube creates (using Kubernetes Client) just empty project (which does not create required OpenShift resources) instead of making request for a new project (this tells OpenShift to create a new project by itself, which creates all required resources as well), this results into the following error:

`error: couldn't get deployment springboot-rest-1: User "system:serviceaccount:itest-9aceb2d1-26df-44e3-b3f0-f50d8088f8e6:deployer" cannot get replicationcontrollers in project "itest-9aceb2d1-26df-44e3-b3f0-f50d8088f8e6"`

When I logged in with oc and tried to look for a replication controller `oc get rc`, it says there is none:
`NAME                DESIRED   CURRENT   AGE
springboot-rest-1   0         0         59s`

**Comment by RadekKoubsky** [comment]
Thanks for your quick reply @dipak-pawar 
I will try it with the latest snapshot.

**Comment by lordofthejars** [comment]
Alpha20 was released yesterday, so when synced with maben central you can
grab it from there. It is already in public jboss nexus

**Comment by iocanel** [comment]
Regarding configuration it shouldn't matter if the user passes the configuration via kubernetes or openshift extension. For example the two examples bellow are equivalent:

      <extension qualifier="kubernetes">
        <property name="env.config.url">file:${project.basedir}/target/classes/META-INF/fabric8/openshift.yml</property>
     </extension>

This is equivalent to:

      <extension qualifier="openshift">
        <property name="env.config.url">file:${project.basedir}/target/classes/META-INF/fabric8/openshift.yml</property>
      </extension>

The only case where it makes a different is when the properties are openshift specific. For example:

- keepAliveGitServer
- definitions
- definitionsFile
- autoStartContainers
- proxiedContainerPorts
- portForwardBindAddress

FWIW, there used to be a relevant bug that I think has been fixed in either Alpha19 or Alpha20.

Now regarding you example, I would just use `env.config.url` to specify the the url to `openshift.yml`. Why? becuase it contains everything you need. You don't need to pass extra depedencies (unless for some reason they are not part of openshift.yml and you definitely don't need to pass a definitionsFile. The definitionsFile is something that is meaningful for `in container` tests, which I am not that familiar with.

**Comment by RadekKoubsky** [comment]
> Now regarding you example, I would just use env.config.url to specify the the url to openshift.yml. Why? becuase it contains everything you need. You don't need to pass extra depedencies (unless for some reason they are not part of openshift.yml and you definitely don't need to pass a definitionsFile. The definitionsFile is something that is meaningful for in container tests, which I am not that familiar with.

This is the problem, FMP generates `openshift.yml`, but also `my-project-is.yml` which contains image stream with the app image. I need to tell Arquillian Cube to read the `my-project-is.yml`, import the app image and then deploy it. I do not know any other way to build and deploy the app image (that is created using FMP) in context "create a separate project per integration test".

The example of multiple config files that worked for me:
`<extension qualifier="kubernetes">
    <property name="env.config.url">file:${project.basedir}/target/classes/META-INF/fabric8/openshift.yml</property>
    <property name="env.dependencies">file:${project.basedir}/target/springboot-rest-is.yml</property>
  </extension>`

Anyway, I will try the Alpha20 and let you know.

**Comment by iocanel** [comment]
In theory fmp should do take care of building the image, creating image streams etc. This is something that should work file if we use an existing project, but it can be problematic if arquillian creates a random project.

It needs some thought.

**Comment by RadekKoubsky** [comment]
@iocanel 
I have discussed this with others in team. We agreed on that the following scenario of using FMP and Arquillian for creating a new it-test namespace is valid an should work from Arquillian perspective.

Lets assume we are not using OpenShift Online, thus we can have more than one project.

A user has two environments (projects), the first one is DEV, their regular workspace. The second one is TEST that is going to be created for each integration test suite.

Expected workflow should be like this:
1) Building the image and creating an image stream
U user builds the image and creates an image stream in their DEV environment using FMP. FMP creates openshift.json, image-stream.json files.

2) Running integration test
A user runs an integration test in the TEST environment that is created by Arquillian for the integration test. Arquillian is configured to consume the openshift.json and image-stream.json file from the previous step. Currently created TEST environment is deleted  after the test.

This is pretty much same thing I described in the first comment and I believe it is doable.

The main problem is the creation of a new project in Arquillian Cube which causes problems with rights and service accounts:
```error: couldn't get deployment springboot-rest-1: User "system:serviceaccount:itest-9aceb2d1-26df-44e3-b3f0-f50d8088f8e6:deployer" cannot get replicationcontrollers in project "itest-9aceb2d1-26df-44e3-b3f0-f50d8088f8e6"```

If you run `oc  get rolebindings -n DEV`, you can see existing roles for the DEV project as it was created using `oc new-project`

If you run the same command for project that was created by Arquillian Cube, it returns empty output, thus there are no roles defined. I believe this is why OpenShift complains about the error above.

Can you please look at the place where Arquillian Cube creates a new project for integration test and see if it really does create a new project in the same way as `oc new-project`. Thanks.

**Comment by Ladicek** [comment]
@RadekKoubsky  is this still valid?

**Comment by bartoszmajsak** [comment]
@Ladicek @RadekKoubsky as https://github.com/fabric8-launcher/launcher-planning/issues/43 was closed do we consider this one fixed?

**Comment by Ladicek** [comment]
Yea I think this has been fixed for quite some time.
