### ISSUE TITLE
[Arquillian Cube - OpenShift] arquillian.xml openshift extension ignores kubernetes properties

### ISSUE THREAD

**Issue by RadekKoubsky** [arquillian/arquillian-cube#635]
Hello,
please take a look at the following [arquillian.xml](https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-openshift/src/test/resources/arquillian.xml#L8) file. I want to use an existing namespace for integration test, thus, I have kubernetes `<property name="env.init.enabled">false</property>` defined within my openshift extension element.

if you run:
oc login
oc new-project my-project
`mvn fabric8:deploy -Popenshift`
and then the integration test
`mvn verify -Popenshift-it -Dnamespace.use.existing=my-project` 

Using the latest snapshot from arquillian cube master, I get:
`Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.185 sec <<< FAILURE! - in org.obsidiantoaster.quickstart.OpenShiftIT
org.obsidiantoaster.quickstart.OpenShiftIT  Time elapsed: 3.184 sec  <<< ERROR!
java.lang.StackOverflowError`

Using Alpha19, I get this in logs:
`Applying kubernetes configuration from: jar:file:/home/rkoubsky/QE/MSA/forks/rest_springboot-tomcat/target/springboot-rest-1.0.0-SNAPSHOT.jar!/META-INF/fabric8/kubernetes.json`

Which says that my `<property name="env.init.enabled">false</property>` was ignored as it tries to deploy infrastructure from kubernetes.json (it should use openshift.json though) instead of using the existing one (I deployed from FMP).

**Comment by dipak-pawar** [comment]
@RadekKoubsky 

There is no need to use snapshot dependency as 1.0.0.Alpha20 is available in maven central.

If you are using k8s or openshift extension, If you have kubernetes.json file available in class path there is no need to provide env.config.url, it will take by default.

If you want to use different file e.g. with name(openshift.json) you have to use `env.config.resource.name
` property. i.e. 
```xml
<property name="env.config.resource.name">openshift.json</property>
```
 > Applying kubernetes configuration from: jar:file:/home/rkoubsky/QE/MSA/forks/rest_springboot-tomcat/target/springboot-rest-1.0.0-SNAPSHOT.jar!/META-INF/fabric8/kubernetes.json

It doesn't mean that openshift extension properties are ignoring. 

could you please try with above option? & let me know.

**Comment by RadekKoubsky** [comment]
Thanks for reply @dipak-pawar 
I am running into several issues while playing with the arquillian cube configuration, I will try to make it clear.

> It doesn't mean that openshift extension properties are ignoring.
My confusion comes from the following functionality:
1) `<property name="env.init.enabled">false</property>` in arquillian.xml
If I run `mvn verify -Popenshift-it -Dnamespace.use.existing=my-project`, I expect that runtime values are:
namespace.use.existing=my-project
env.init.enabled=false

However, the `env.init.enabled` is not set from arquillian.xml, that's why Arquillian Cube tries to init the environment and reads the `kubernetes.json`  (it appears in logs)

My conclusion is that the openshift extension ignores kubernetes properties within the arquillian.xml

2) env.init.enabled passed from mvn command
If I run `mvn verify -Popenshift-it -Dnamespace.use.existing=my-project -Denv.init.enabled=false`, the `env.init.enabled` property is set as there is no log about reading `kubernetes.json`, thus it does not try to init environment I believe. However, doing this results into #636 

I just tried the commands above with 1.0.0.Alpha20

I will try to use the `env.config.resource.name` property, but for my use case I either use existing namespace (arquillian.xml vs maven properties) or I want to use a new temporary one (this brings me back to #633 )

> If you are using k8s or openshift extension, If you have kubernetes.json file available in class path there is no need to provide env.config.url, it will take by default.

I would expect the same behavior for the openshift extension and the openshift.json file. However, it is not happening, I belive #634 solves this problem.

**Comment by lordofthejars** [comment]
Two things about this 
1) can you update to 1.6.0
2) if you want to use system properties in `arquillian.xml` you need to do it like:

`<property name="env.init.enabled">${init.enabled:true}</property>`

and then in Maven `-Dinit.enabled=false`

**Comment by RadekKoubsky** [comment]
After updating to 1.6.0, works like a charm! Properties from arquillian.xml are not ignored anymore, the openshift extension scans the openshift.json file, and test run with success, thanks a lot. 

I have two notes:

1) Warnings in logs
Is it posible to get rid of the warning and "could not annotate" logs? I suppose the second one is due to permissons, see log from test:
```
Running io.openshift.booster.OpenShiftIT
Initializing Session:95541e47-3c6d-428e-bb2f-616103feeade
Using Kubernetes at: https://api.devel.xpaas:8443/
Replication controller: [spring-boot-http-1]
Pod: [spring-boot-http-1-sn5tw] Status: [Running]
Pod: [spring-boot-http-s2i-1-build] Status: [Succeeded]
Service: [spring-boot-http] IP: [172.30.119.131] Ports: [ 80 ]
Jun 21, 2017 4:27:01 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for OpenShiftSuiteLifecycleController.startAutoContainers is null. It won't be invoked.
Could not annotate namespace:[rkoubsky] with test: [io.openshift.booster.OpenShiftIT] method: [testGreetingEndpointWithNameParameter] state:[RUNNING]
Could not annotate namespace:[rkoubsky] with test: [io.openshift.booster.OpenShiftIT] method: [testGreetingEndpointWithNameParameter] result:[PASSED]
Could not annotate namespace:[rkoubsky] with test: [io.openshift.booster.OpenShiftIT] method: [testGreetingEndpoint] state:[RUNNING]
Could not annotate namespace:[rkoubsky] with test: [io.openshift.booster.OpenShiftIT] method: [testGreetingEndpoint] result:[PASSED]
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.335 sec - in io.openshift.booster.OpenShiftIT
Jun 21, 2017 4:27:05 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for OpenShiftSuiteLifecycleController.stopAutoContainers is null. It won't be invoked.
Could not annotate namespace: [rkoubsky] with status: [PASSED].
Destroying Session:95541e47-3c6d-428e-bb2f-616103feeade

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
```
2) Openshift client versions
I explicitly declare openshift-client version in my [pom](https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-openshift/pom.xml#L121) and then importing this client within my test class. This is fine.
When I tried to use openshift-client (io.fabric8.openshift.clnt.v2_2.OpenShiftClient) from the shaded uberjar I got the following exception:
```
testGreetingEndpointWithNameParameter(io.openshift.booster.OpenShiftIT)  Time elapsed: 0.04 sec  <<< ERROR!
java.lang.RuntimeException: Could not set value on field io.fabric8.openshift.clnt.v2_2.OpenShiftClient io.openshift.booster.OpenShiftIT.client using io.fabric8.kubernetes.clnt.v2_2.DefaultKubernetesClient@7a26928a
```
If doing this is not recommended, I am fine, just want to make sure it is expected behavior.

**Comment by RadekKoubsky** [comment]
I have verified the latest comment with Arquillian Cube 1.8.0. Warning logs disappeared, I assume explicit declaration of openshift/kubernetes-client is recommended. Thanks for fixing it!
