### ISSUE TITLE
[Arquillian Cube - OpenShift] Could not set value on field io.fabric8.openshift.client.OpenShiftClient

### ISSUE THREAD

**Issue by RadekKoubsky** [arquillian/arquillian-cube#636]
##### Issue Overview

When I want to use io.fabric8.openshift.client.OpenShiftClient within my [integration test](https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-openshift/src/test/java/org/obsidiantoaster/quickstart/OpenShiftIT.java#L33), it throws:
`java.lang.RuntimeException: Could not set value on field io.fabric8.openshift.client.OpenShiftClient org.obsidiantoaster.quickstart.OpenShiftIT.client using io.fabric8.kubernetes.client.DefaultKubernetesClient@4a183d02`

##### Steps To Reproduce
clone my example from here https://github.com/RadekKoubsky/rest_springboot-tomcat/tree/arquillian-cube-integration-test-openshift

```
oc login
oc new-project my-project
mvn fabric8:deploy -Popenshift
mvn verify -Popenshift-it -Dnamespace.use.existing=my-project -Denv.init.enabled=false
```

<details>
 Tried with latest built of ArquillianCube master https://github.com/arquillian/arquillian-cube 
</details>

**Comment by lordofthejars** [comment]
Ioannis did some changes on this can you try to update to cube 1.2.0 (released today) and check https://github.com/arquillian/arquillian-cube/blob/577b49e73fb6d6ff81f47b60b9cb51e20ab007b1/openshift/ftest-standalone/src/test/java/org/arquillian/cube/openshift/standalone/HelloWorldTest.java 

Notice also this warning http://arquillian.org/arquillian-cube/#_dealing_with_version_conflicts if you look closely you'll see that the ftest I sent you are using this internal class.

**Comment by RadekKoubsky** [comment]
Thanks for the info @lordofthejars 
I changed my arq cube version to [1.2.0](https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-openshift/pom.xml#L45) and updated my test to use OpenShift client from the shaded uber jar (v2.2.12), however, getting the same exception:
```
java.lang.RuntimeException: Could not set value on field io.fabric8.openshift.clnt.v2_2.OpenShiftClient org.obsidiantoaster.quickstart.OpenShiftIT.client using io.fabric8.kubernetes.clnt.v2_2.DefaultKubernetesClient@73d69c0f
```

Where does the class in `@RunWith(ArquillianConditionalRunner.class)` and the requires annotation `@RequiresOpenshift` (I can use only `@RequiresKubernetes`) come from? I can't find it on my class path, I use these arq dependencies in my `pom.xml`:

```
<dependency>
      <groupId>org.jboss.arquillian.junit</groupId>
      <artifactId>arquillian-junit-container</artifactId>
      <version>1.1.12.Final</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.arquillian.cube</groupId>
      <artifactId>arquillian-cube-openshift</artifactId>
      <type>pom</type>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <artifactId>undertow-core</artifactId>
          <groupId>io.undertow</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by lordofthejars** [comment]
http://arquillian.org/arquillian-cube/#_requirements_module

**Comment by RadekKoubsky** [comment]
Thanks, I added the requirement dependency which let me use `@RunWith(ArquillianConditionalRunner.class)`, but encountered other problems:

a) I have `arquillian-cube-bom` defined in my pom.xml, but if I do not specify `<version>1.2.0</version>` in the `arquillian-cube-requirement` dependency, maven complains:
```
[ERROR]   The project org.obsidiantoaster.quickstart:springboot-rest:1.0.0-SNAPSHOT (/home/rkoubsky/QE/MSA/forks/rkoubsky/rest_springboot-tomcat/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.arquillian.cube:arquillian-cube-requirement:jar is missing
```

I tried to delete .m2 cache, did not help. Is this a problem with the bom or am I missing something?

b) I still do not have `@RequiresOpenshift` on classpath, I suppose the annotation is located in the `arquillian-cube-openshift` dependency as `@RequiresKubernetes` is in the `arquillian-cube-kubernetes` dependency.

**Comment by lordofthejars** [comment]
Arquilliam bom contains the requirements module https://github.com/arquillian/arquillian-cube/blob/master/bom/pom.xml#L78. So it is strange it is happening this, we should see the whole pom to see what is happening. Regarding annotation, it is located at https://github.com/arquillian/arquillian-cube/blob/master/openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/requirement/RequiresOpenshift.java

**Comment by dipak-pawar** [comment]
@RadekKoubsky Can you share your pom.xml?

**Comment by RadekKoubsky** [comment]
Sure, here is [pom.xml](https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-openshift/pom.xml) within my repo, branch "arquillian-cube-integration-test-openshift".

I am verifying it using the steps from the fist comment.

**Comment by lordofthejars** [comment]
https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-openshift/pom.xml#L116 this should not be pom type but the default one (jar)

**Comment by RadekKoubsky** [comment]
When I remove the pom type from the openshift extension dependency, the jars disappear from classpath. On the other hand, the requirement dependency does not have pom type (but have version defined), but its jars exist in the project. I must be missing something (I really tried to follow documentation).

Btw the pom has defined jboss-parent as parent pom.

**Comment by lordofthejars** [comment]
Ok then let's do another thing, try to avoid using bom and use directly the
jars as used in
https://github.com/arquillian/arquillian-cube/blob/master/openshift/ftest-standalone/pom.xml
but
adding the version of course-

El dc., 10 de maig 2017 a les 13:13, Radek Koubsky (<
notifications@github.com>) va escriure:

**Comment by dipak-pawar** [comment]
@RadekKoubsky Thank you. I have added fix for the issue which you are facing. If you are interested look #692

**Comment by RadekKoubsky** [comment]
@dipak-pawar Thanks for fixing it.

@lordofthejars I have been able to run integration test with dependencies you provided, thanks. However, there is still unexpected behavior regarding kubernetes client, I have created another branch [here](https://github.com/RadekKoubsky/rest_springboot-tomcat/blob/arquillian-cube-integration-test-2/pom.xml)

When I run the following command:
```
mvn fabric8:deploy -Popenshift
mvn verify -Popenshift-it (using existing namespace is hardcoded in arquillian.xml)
```
I get different results.

1) Successfull run
Output:
```
Running io.openshift.booster.OpenShiftIT
Initializing Session:1fc75059-216a-46de-b16e-d7bcd108f376
Using Kubernetes at: https://api.devel.xpaas:8443/
Creating kubernetes resources inside namespace: rkoubsky
if you use OpenShift then type this switch namespaces:     oc project rkoubsky
if you use kubernetes then type this to switch namespaces: kubectl config set-context `kubectl config current-context` --namespace=rkoubsky
Replication controller: [spring-boot-http-1]
Pod: [spring-boot-http-1-0n1bd] Status: [Running]
Pod: [spring-boot-http-s2i-1-build] Status: [Succeeded]
Service: [spring-boot-http] IP: [172.30.36.116] Ports: [ 80 ]
May 10, 2017 5:06:53 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for OpenShiftSuiteLifecycleController.startAutoContainers is null. It won't be invoked.
Could not annotate namespace:[rkoubsky] with test: [io.openshift.booster.OpenShiftIT] method: [testRunningPod] state:[RUNNING]
Test pod is running.
OpenShift client version: class io.fabric8.openshift.clnt.v2_2.DefaultOpenShiftClient
Could not annotate namespace:[rkoubsky] with test: [io.openshift.booster.OpenShiftIT] method: [testRunningPod] result:[PASSED]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.402 sec - in io.openshift.booster.OpenShiftIT
May 10, 2017 5:06:55 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for OpenShiftSuiteLifecycleController.stopAutoContainers is null. It won't be invoked.
Could not annotate namespace: [rkoubsky] with status: [PASSED].
Destroying Session:1fc75059-216a-46de-b16e-d7bcd108f376
```

Pay attention to log: `OpenShift client version: class io.fabric8.openshift.clnt.v2_2.DefaultOpenShiftClient`

This is correct as arquilian cube injects this into `public interface OpenShiftClient` field.

I have concerns about the warnings, but this is not important in this context I guess.

2) Unsucessfull run
Output:
```
Running io.openshift.booster.OpenShiftIT
Initializing Session:1d3238da-dd86-4756-8e1c-e9a419fc4ee8
Using Kubernetes at: https://api.devel.xpaas:8443/
Creating kubernetes resources inside namespace: rkoubsky
if you use OpenShift then type this switch namespaces:     oc project rkoubsky
if you use kubernetes then type this to switch namespaces: kubectl config set-context `kubectl config current-context` --namespace=rkoubsky
Replication controller: [spring-boot-http-1]
Pod: [spring-boot-http-1-0n1bd] Status: [Running]
Pod: [spring-boot-http-s2i-1-build] Status: [Succeeded]
Service: [spring-boot-http] IP: [172.30.36.116] Ports: [ 80 ]
May 10, 2017 5:07:14 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for OpenShiftSuiteLifecycleController.startAutoContainers is null. It won't be invoked.
May 10, 2017 5:07:14 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for UpdateTestResultBeforeAfter.update is null. It won't be invoked.
May 10, 2017 5:07:14 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for UpdateTestResultBeforeAfter.update is null. It won't be invoked.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.496 sec <<< FAILURE! - in io.openshift.booster.OpenShiftIT
testRunningPod(io.openshift.booster.OpenShiftIT)  Time elapsed: 0.036 sec  <<< ERROR!
java.lang.RuntimeException: Could not set value on field io.fabric8.openshift.clnt.v2_2.OpenShiftClient io.openshift.booster.OpenShiftIT.client using io.fabric8.kubernetes.clnt.v2_2.DefaultKubernetesClient@17f9344b

May 10, 2017 5:07:14 PM org.jboss.arquillian.core.impl.ObserverImpl resolveArguments
WARNING: Argument 1 for OpenShiftSuiteLifecycleController.stopAutoContainers is null. It won't be invoked.
Could not annotate namespace: [rkoubsky] with status: [PASSED].
Destroying Session:1d3238da-dd86-4756-8e1c-e9a419fc4ee8
```

Arquillian obviously tries to inject `io.fabric8.kubernetes.clnt.v2_2.DefaultKubernetesClient` into `OpenShiftClient` interface field.

Is this behavioir caused by wrong configuraton? Is it related to `kubernetes.client.creator.class.name` arquillian configuration property?

FYI: I have two kubernetes clients in project right now, one comes from `kubernetes-openshift-uberjar:2.2.12`, the other one from `openshift-test-utils:1` -> `openshift-client:1.4.34` -> `kubernetes-client:1.4.34`

**Comment by lordofthejars** [comment]
@iocanel Do you know why this is happens ?

**Comment by RadekKoubsky** [comment]
This has been verified as a part of #635 Solution: explicitly declare openshift/kubernetes-client within your pom to have control what version you use
