### ISSUE TITLE
Implement a feedback mechanism when the Kubernetes/Openshift environment initialization timesout.

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#639]
Sometimes a build may fail due to timeout. Looking at the console and seeing the pod, service etc that timed out doesn't really help. 

It would be amazing if we could grab the logs and events of the pod that is responsible for the timeout.

**Comment by lordofthejars** [comment]
https://github.com/arquillian/arquillian-cube/pull/642
