### ISSUE TITLE
Execute tests over docker server address

### ISSUE THREAD

**Issue by rbattenfeld** [arquillian/arquillian-cube#64]
In case the docker container is not available remotely, execute the tests by using the ip address of the docker host instead of the ip address of the started docker container.

Perhaps this can be solved by adding a dedicated property which overrides the default behavior. This should then also update the injected ArquillianURL address.

**Comment by aslakknutsen** [comment]
This is similar/duplicate to #52

**Comment by rbattenfeld** [comment]
Correct. I didn't see this one.

**Comment by lordofthejars** [comment]
No problem, nice to see that we are on the path. I close this issue then :).
