### ISSUE TITLE
Request hangs calling 2 times with arquillian-cube-kubernetes with port forwarding in same test

### ISSUE THREAD

**Issue by cougil** [arquillian/arquillian-cube#641]
Bug report

##### Issue Overview

We are using Rest-assured with Arquillian-cube and Arquillian-cube-kubernetes in order to verify that our microservice deployed into k8s works as expected. 

We have found that we are not able to run 2 different requests in the same test, may be because of the PortForwarding mechanism, after running the 1st request, the 2nd doest not work properly. Once the first request succeed, the URL didn't change and may be because of that the next request didn't work properly: we have been waiting more than 5 minutes and the test didn't finish (it seems that the request is waiting for something pending to close). 

In that exact moment we tried to use the same URL externally (using another tool like curl) and the service didn't reply anything, so it seems that "something" from Arquillian is not forwarding the request properly to the service. May be the problem is how is managed the PortForwarding mechanism? 

Here you can see how our test is annotated:

````
    @Named("our_service")
    @PortForward
    @ArquillianResource
    private URL url;
````

And here you can see the example of the 2 same request we are using (which should be useful for example for typical requests that must be logged in first):

````
    @Test
    public void get_token_info_with_valid_token(){

        // 1st request that works
        String token = validLogin();

        // 2nd request that never ends...
        TokenInfo tokenInfo = given()
                                .auth().oauth2(token)
                            .when()
                                .get(TokensResource.PATH)
                            .then()
                                .statusCode(Response.Status.OK.getStatusCode())
                                .extract().as(TokenInfo.class);

        assertThat(tokenInfo)
                .isNotNull();
    }

 private String validLogin() {
        //... ourRequest ...
        return given()
                .body( ourRequest .... )
                .contentType(ContentType.JSON)
                .when()
                .post(UserAuthenticationResource.PATH)
                .then()
                .statusCode(Response.Status.OK.getStatusCode())
                .extract()
                .as(String.class);
    }

````

We have verified also that using Jersey client, the behaviour is the same.

##### Expected Behaviour

The second request using the ArquillianResource should work as the 1st one, finishing and giving a result.

##### Current Behaviour

The second request never ends, hangs without no response.

##### Steps To Reproduce
1. Create a project with all the specified dependencies
2. Create a Arquillian test with PortForwarding enabled that uses 2 times the same request on the same test
3. Run the test and wait for the 2nd response

##### Additional Information

Versions
```
java: 1.8
rest-assured: 3.0.1
arquillian-cube: 1.0.0.Alpha20
arquillian-cube-kubernetes: 1.0.0.Alpha20
```

Best regards!

**Comment by iocanel** [comment]
@cougil: I modified https://github.com/arquillian/arquillian-cube/blob/6fef22f15073a58997db9ca436bdfc5dbc634926/kubernetes/ftest-kubernetes/src/test/java/HelloWorldTest.java#L48-L47 so that it does the call multiple times, but I wan't able to reproduce the issue. I even made sure that after each call I gracefully stop the client etc and don't see any issue.

**Comment by lordofthejars** [comment]
@cougil Can you try to put a debug point at first line of the test, then execute manually using curl, Postman or any CLI tool the test (Exactly the same with same parameters and so on) and see if you get the same result or not. Just to try to find if the problem might be in using REST-Assured, or maybe in a JVM, or any other strange thing. This kind of errors usually are because there are a slightly difference that makes everything fails.

Another option if it is possible if to provide a failing example that we can debug.

**Comment by cougil** [comment]
Hi dudes!

We've checked that something weird is happening in our environment: the pods (we need 2 because one depends of a DB) already started correctly before the test launches. Also after we put a breakpoint in the first line of the test and we verified that we can call the microservice using another CLI tool (`curl` in our case) and the service works as expected. The problem again is if we continue with the test, the 1st requests we can get its response, but the 2nd one it hangs/never ends. 

Also, we noticed that the number of threads that are doing some port forwarding work they are always growing, which we suppose is not the correct behaviour:

![image](https://cloud.githubusercontent.com/assets/2370634/24350473/a36a695a-12e2-11e7-93ba-1654cb6ae652.png)

Ah! We have had to define some timeouts (`wait.for.service.connection.timeout`) because this simple test takes too long to boot up ending with both 2 pods running.

We will try to share with you some details to see what we are doing and how in order to look for where is the problem, but basically we are running a microservice built on top of Spring boot (and in your example I think you have a PHP webserver ;-)) with Java8 using Arquillian and fabric8 plugin in order to build & deploy the containers in our own (loca) cluster. Also another detail is that we are trying to run everything against our machine using minikube (0.17.1), which we don't know if this is the best option to work with k8s or not...

Best,

**Comment by cougil** [comment]
I think we found the issue: the problem was that there were some dependency problems with `Spring platform` (we are using _Athens-RELEASE_) &| `Spring-cloud` (we were using _Camden.SR3_) and some libraries were overrided by the ones provided by Spring. We were including this dependencies while running `Arquillian` tests:

        ```
    <dependency>
                <groupId>io.spring.platform</groupId>
                <artifactId>platform-bom</artifactId>
                <version>${spring.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- end Spring boot -->

            <!-- spring cloud -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        ```

also this configuration provoques to us to add the following exclusion with `arquillian cube`, because of an exception we receive trying to run the tests:
```
       <dependency>
            <groupId>org.arquillian.cube</groupId>
            <artifactId>arquillian-cube-kubernetes</artifactId>
            <scope>test</scope>
            <!-- Without this exclusion we get the error Exception in thread "main" java.lang.AbstractMethodError at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally -->
            <exclusions>
                <exclusion>
                    <groupId>org.apache.maven</groupId>
                    <artifactId>maven-aether-provider</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

also, we have to include `undertow` because of the Spring boot:
```
        <!-- arquillian has undertow-core dependency. Spring boot finds this dependency and tries to load UndertowEmmbeddedServlectContainerFactory which needs undertow-servlet-->
        <dependency>
            <groupId>io.undertow</groupId>
            <artifactId>undertow-servlet</artifactId>
            <version>1.3.25.Final</version>
            <scope>test</scope>
        </dependency>
```
and then after all include the `kubernets client`, but excluding the `okhttp`:
```
        <!--kubernetes client-->
        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>2.2.6</version>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- arquillian requires version 3.6.0 but kubernetes-client has as dependency version 3.3.1 -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.6.0</version>
        </dependency>
```

So, finally, you will wondering how we fixed this issue? Easy: we have created a new module apart from our "rest/API" module and then including only the Arquillian dependencies. And then everything has worked perfecly ;-)

**Comment by lordofthejars** [comment]
:) cool thank you very much for everything.  In fact I always suggest to maintain the independence of everything create a core module which only contains business code and unit tests and then create one new module for each kind of tests.
