### ISSUE TITLE
Possibility for more custom strategies besides customAwaitStrategy. (E.G customBeforeStopStrategy)

### ISSUE THREAD

**Issue by jelmew** [arquillian/arquillian-cube#646]
##### Issue Overview

BeforeStop events can be very restrictive at times. For integration with jacoco-agent, we would like to be able to send an request to the container (POST call) to shut down the jvm before we stop the container, so that some information is more complete.  There already is an AwaitStrategy that can be implemented, for custom AwaitStrategies. would something similar also be possible for beforeStop?

Example:

beforeStop:
 - copy: ....
- log: ...
 -  my.own.package.name.CustomBeforeStopStrategy:

If this is easily implementable, I can try to make a pull request myself.

**Comment by lordofthejars** [comment]
Hi, first of all thank you very much for using Cube. So first of all please feel free to provide a PR, they are more than welcome, and we can help you in anything. 

Second really nice use case, are you planning to write about it?

Finally notice that if you are using in-container approach (`@Deployment method`) (not standalone) you can use https://github.com/arquillian/arquillian-extension-jacoco and should provide everything out of the box.

**Comment by jelmew** [comment]
Hi,
I'll try try to make something for a PR, it seems like a nice exercise.

**Comment by jelmew** [comment]
Hi, I made a rudimentary implementation. It is still WIP, but I wanted to check if the general idea is a good one.
