### ISSUE TITLE
Getting Stackoverflow while running ftests k8s with .yaml extension

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-cube#653]
##### Issue Overview

Tell us briefly what the problem is about.

##### Expected Behaviour
Ftests should run fine.

##### Current Behaviour
Getting Stackoverflow error while running ftests.

##### Steps To Reproduce
1.Run ftest

**Comment by bartoszmajsak** [comment]
We need findbugs integrated... Thanks @dipak-pawar
