### ISSUE TITLE
Multiple service implementations found for interface org.jboss.arquillian.container.spi.client.container.DeployableContainer

### ISSUE THREAD

**Issue by dcdh** [arquillian/arquillian-cube#661]
##### Issue Overview
Hello, I am unable to execute an arquillian cube container on my wildfly swarm project.

##### Expected Behaviour
My integration test are executed under docker containers.
##### Current Behaviour
When launching my test using *mvn integration-test* un exception is raised:

<details>
java.lang.RuntimeException: Could not create new instance of class org.jboss.arquillian.test.impl.EventTestRunnerAdaptor
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.jboss.arquillian.container.impl.ContainerCreationException: Could not create Container containerless
Caused by: java.lang.IllegalStateException: Multiple service implementations found for interface org.jboss.arquillian.container.spi.client.container.DeployableContainer. org.arquillian.cube.impl.containerless.ContainerlessDockerDeployableContainer, org.wildfly.swarm.arquillian.adapter.WildFlySwarmContainer
</details>

##### Steps To Reproduce
1. unzip the project linked with this issue
2. do 'mvn integration-test'

##### Additional Information
I have setup the project using this sample *https://github.com/aslakknutsen/cube-wildfly-swarm* However it failed to execute because the last version of Swarm contains an embedded implementation of DeployableContainer. It clashes because Arquillian doesn't know which implementation to use between the one provided by swarm and the one provided by arquillian-cube-containerless (ContainerlessDockerDeployableContainer).

I have search about an example of last swarm version with arquillian cube example without success. Is it possible to have a working sample ?
[todosappmonorepo.zip](https://github.com/arquillian/arquillian-cube/files/891631/todosappmonorepo.zip)

**Comment by lordofthejars** [comment]
Hi, the problem is that you are configuring Arquillian with two Deployable Containers. You need to choose one or another. In your case the two containers are wildfly swarm and cube containerless.

```xml
<dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>arquillian</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.codehaus.plexus</groupId>
                    <artifactId>plexus-utils</artifactId>
                </exclusion>
            </exclusions>
 </dependency>

<dependency>
	<groupId>org.arquillian.cube</groupId>
	<artifactId>arquillian-cube-containerless</artifactId>
	<scope>test</scope>
</dependency>
```
 
Since I suppose you want to run tests using Docker, then you'll need to remove `org.wildfly.swarm:arquillian`. Notice that if you want to develop both kind of tests, one possible approach would be creating them in two different modules to get classpath isolated.
