### ISSUE TITLE
Uncaught ExecutionException in CubeDockerConfigurator 

### ISSUE THREAD

**Issue by jamesnetherton** [arquillian/arquillian-cube#664]
##### Issue Overview

Similar to #660. When cube initializes, it runs through [`CubeDockerConfigurator.configure`](https://github.com/arquillian/arquillian-cube/blob/8bcf1960df5be7b2536884e4d2d3513ae21e53cb/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/CubeDockerConfigurator.java#L63). The potential exists for executables like docker-machine or Boot2Docker to not be available. When this happens, tests fail whether they need to make use of Arquillian Cube or not.

This prevents a test suite being composed from a mix of tests where some use Arquillian Cube and some that do not. 

##### Expected Behaviour

ExecutionException is trapped and logged, enabling the test to proceed. 

##### Current Behaviour

Uncaught ExecutionException is thrown which prevents tests that do not use Arquillian Cube from running.

**Comment by lordofthejars** [comment]
http://arquillian.org/blog/2017/04/06/arquillian-cube-1-1-0/
