### ISSUE TITLE
Change containerId to a value type (only) for Injecting into custom strategies for easier implementation creation.

### ISSUE THREAD

**Issue by jelmew** [arquillian/arquillian-cube#671]
##### Issue Overview

The containerId as used through the code is an String. This is all fine and dandy,  but when the user implements his or her own BeforeStopAction, this can become a problem when the user adds more String fields.
##### Expected Behaviour

    public class Test implements BeforeStopAction {
        private final String somethingUsedInTheImplementation = "Something";
        private ContainerId containerId;

        private DockerClientExecutor dockerClientExecutor;
    
       public Test() {
        }
    }

Which would behave fine with reflection.
##### Current Behaviour
    public class Test implements BeforeStopAction {
        private final String somethingUsedInTheImplementation = "Something";
        private String containerId;

       private DockerClientExecutor dockerClientExecutor;
       public Test() {
      }
    }

Gives errors like : "Caused by: java.lang.IllegalArgumentException: java.lang.IllegalAccessException: Can not set static final java.lang.String field Test.USERNAME to java.lang.String: and so, since the injection looks for a String and it thinks it can inject it.

##### Additional Information
Shall I make an pull request to remedy this for the customBeforeStopAction as cleanup? Or would it be preferable to change containerId to another class on a more global scope, since the containerId might be used for more custom strategies in the future?
```

**Comment by lordofthejars** [comment]
Yes what you can use is `CubeId ` as parameter and `https://github.com/arquillian/arquillian-cube/blob/master/core/src/main/java/org/arquillian/cube/impl/model/DefaultCubeId.java` as implementation.

**Comment by jelmew** [comment]
If I had known that DefaultCubeId existed, I would have used that immediately. :P. I'll make a small pull request to improve this.

**Comment by lordofthejars** [comment]
:) thank you so much.
