### ISSUE TITLE
Arquillian initialization ends in infinite loop when a test class has a parent

### ISSUE THREAD

**Issue by jpechane** [arquillian/arquillian-cube#696]
As a reproducer please try this project - https://github.com/jpechane/arquillian-cube-standalone-example

The problem is located in Reflectionutil.isClassWithAnnotation. When this method is called there is a line in loop - `nextSource = source.getSuperclass()`. When the test class has a parent then the first iteration returns Parent2 class and subsequent iterations return the very same class! thus ending in infinite loop.

IMHO the should code would be
```
                Class<?> nextSource = source;
                while (nextSource != Object.class) {
                    if (nextSource.isAnnotationPresent(annotationClass)) {
                        return true;
                    }
                    nextSource = nextSource.getSuperclass();  // Move up in hierarchy
                }
```

**Comment by bartoszmajsak** [comment]
Thanks for reporting and detailed analysis. Would you be interested in sending PR with these changes?

**Comment by jpechane** [comment]
Done in #697
