### ISSUE TITLE
Can we configure arquillian to restart docker daemon before running containers?

### ISSUE THREAD

**Issue by RajAsapu** [arquillian/arquillian-cube#718]
I have a scenario where i need to restart my docker daemon before starting up my containers . Do we have a way to do that using arquillian xml configuration.

**Comment by lordofthejars** [comment]
Not sure if this should be implemented inside Cube or it so something so specific to your use case. Let me think about it. 

Thank you very much for using Cube.

**Comment by lordofthejars** [comment]
Hello, after thinking about it., for me this is more a build step or something related to before suite, since probably restarting the Docker daemon implies some OS calls.

For this reason I think that this is not something to be provided by Arquillian Cube core.
