### ISSUE TITLE
should the kubernetes/openshift based testing stuff move to its own separate sub project, `arquillian-kube`?

### ISSUE THREAD

**Issue by jstrachan** [arquillian/arquillian-cube#729]
when I look at the docs:
http://arquillian.org/arquillian-cube/

the contents on the left is all about pure docker testing and much of it is of no relevance to users of kubernetes/openshift.

I wonder if we should split the docs into 2 so that for folks using kubernetes/openshift/minikube/minishift there's a set of docs aimed purely at their use case?

e.g. at http://arquillian.org/arquillian-kube/?

**Comment by iocanel** [comment]
makes sense to me.
love the name btw :-)

**Comment by lordofthejars** [comment]
Currently chapter 20 and 21 is just for Kubernetes and Openshift, so documentation reflects also this part.

But I understand also that we might change K8s and OpenShift to different project. Let me put @bartoszmajsak on the list, but in my opinion we can split it without much problem as we had Arquillian Cube Q.

**Comment by jstrachan** [comment]
even if we just had 2 separate distros of the docs; one without all the vanilla docker stuff which is of little value to folks on kubernetes/openshift - then had 2 URLs so folks using k8s don't see all the noise about boot2docker etc

**Comment by lordofthejars** [comment]
Sure,

**Comment by bartoszmajsak** [comment]
Is it only about splittings the docs or also the project as such?

**Comment by jstrachan** [comment]
I don't know enough about the code to know how best to organise it; but docker and kubernetes are very different. 

With docker there's single node stuff, there's compose and swarm.  With kubernetes/openshift its all very different (e.g. starting with minikube/minishift, no need to even install docker tooling) - so it feels like they should be 2 separate projects and focusses to me. Am sure there'll be some shared code and stuff; but from an end user they seem totally different.

**Comment by bartoszmajsak** [comment]
So maybe we can think about re-organizing the docs instead? The overall idea with the move of fabric8 bits (as discussed with @iocanel back in the days) to this repository was to have one tool for testing "anything containers".
