### ISSUE TITLE
ForkJoin autostart containers

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#73]
In case of autostart containers, which are containers that are used for the test but they are not the application server itself, (for example database, mail server. ...), they are started one by one sequentially.  If these containers don't have a relationship between them (that is no link section) then maybe we could start all of them in parallel.

This is something we may study to improve the performance of starting the whole scenario.

**Comment by aslakknutsen** [comment]
See org.jboss.arquillian.core.api.threading.ExecutionService
