### ISSUE TITLE
How to access environment variables using CUBE definition format?

### ISSUE THREAD

**Issue by RajAsapu** [arquillian/arquillian-cube#730]
I am having my docker-compose file and i have configured it to be in CUBE format , i need to access the tag names of images from the environment variables which i was not able to do when i use CUBE format.I was able to get the values when i use COMPOSE format.Please let  me know how we could access environment variables up on using CUBE format.

Arquillian.xml
`<?xml version="1.0"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://jboss.org/schema/arquillian"
            xsi:schemaLocation="http://jboss.org/schema/arquillian
  http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <extension qualifier="docker">
        
        <property name="clean">true</property>
        <property name="dockerContainersFile">src/test/resources/docker-compose.yml</property>
        <property name="definitionFormat">CUBE</property>
        <property name="cleanBuildImage">true</property>
        <property name="autoStartContainers">engine</property>
        <property name="cubeSpecificProperties">
            engine:
                await:
                    strategy: log
                    match: 'Message broker is not set up'
                    sleepPollingTime: 5 s
                    iterations: 5
                    stdOut: true
                    stdErr: true
                    timeout: 1800
        </property>
    </extension>
</arquillian>`

docker-compose:
```
`engine:
    image: "epe-price-engine:${ENGINE_IMAGE_TAG}"
    exposedPorts: [8081]
    portBindings: [8081->8081/tcp]
    alwaysPull: true
    env:
        - server.port=8081`
```

Error :  java.lang.IllegalArgumentException: The template variable 'ENGINE_IMAGE_TAG' has no value

Note : It works when i change format to COMPOSE.

**Comment by lordofthejars** [comment]
I suppose that you change to COMPOSE and also adapt the format right? Notice that if you are using compose format you don't need to add specific cube properties, you can put them directly on that file.

I think that in Cube format environment variable is not implemented. I am going to check, and if not then implement it.

Also it is really important to identify the cause if you can paste the whole stacktrace.

Thank you very much for helping improving Cube.

**Comment by lordofthejars** [comment]
Ok, this is a bug we are going to fix ASAP. As a workaround you can use compose format.

**Comment by RajAsapu** [comment]
@lordofthejars : Sure , i will make sure i paste stack trace from now on.Thank you.Let me know if you need further information.

**Comment by lordofthejars** [comment]
Not for this issue :) but just because with stack trace it is easy to go directly to the line where the exception occurred and start working on fix quickly :)

**Comment by RajAsapu** [comment]
@lordofthejars : When can i expect this release 1.6.0 in maven ?

**Comment by lordofthejars** [comment]
It is already there 💃

**Comment by RajAsapu** [comment]
@lordofthejars Sorry to bother you again . I am referring to this maven link [https://mvnrepository.com/artifact/org.arquillian.cube/arquillian-cube-docker](url) and i couldnt see 1.6.0.Please let me the maven url if possible.

**Comment by lordofthejars** [comment]
No worries, we are here to help. http://search.maven.org/#artifactdetails%7Corg.arquillian.cube%7Carquillian-cube-docker%7C1.6.0%7Cjar
