### ISSUE TITLE
Docker drone is expecting the wrong responseCode for Selenium 3.4.0 

### ISSUE THREAD

**Issue by jollytoad** [arquillian/arquillian-cube#736]
Docker-Drone fails to detect that selenium-chrome-debug has started with Selenium 3.4.0.
In https://github.com/arquillian/arquillian-cube/blob/8bcf1960df5be7b2536884e4d2d3513ae21e53cb/docker/drone/src/main/java/org/arquillian/cube/docker/drone/SeleniumContainers.java#L163 the await is set to expect a response code of 403, but it seems that may no longer be the case in 3.4.0, instead you get a 200.

I also can't seem to override the await in the arquillian.xml docker configuration 

After setting a breakpoint on that line and manually overriding the responseCode via the debugger, it seems to work.

**Comment by lordofthejars** [comment]
Thank you so much, yes in case of drone integration, you cannot configure it in `arquillian.xml`. PRs are more than welcome would you like to send a PR just fixing this? The thing is that should be something like if seleniumVersiion is < 3.5.0 then use 403 else 200.

**Comment by jollytoad** [comment]
I'm not sure exactly which version of Selenium this changed in, and unfortunately don't have time to investigate atm.

I managed to override with an extension for the time being...

```java
public class CubeDroneHackExtension implements LoadableExtension {
    @Override
    public void register(LoadableExtension.ExtensionBuilder extensionBuilder) {
        extensionBuilder.observer(CubeDroneHack.class);
    }
}
```

```java
public class CubeDroneHack {
    @Inject
    @ApplicationScoped
    InstanceProducer<SeleniumContainers> seleniumContainersInstanceProducer;

    public void install(@Observes(precedence = 80) CubeDockerConfiguration configuration) {
        final SeleniumContainers seleniumContainers = seleniumContainersInstanceProducer.get();
        final CubeContainer seleniumContainer = seleniumContainers.getSeleniumContainer();
        seleniumContainer.getAwait().setResponseCode(200);
    }
}
```

**Comment by georgwolf** [comment]
The behaviour has been changed with Selenium 3.x.
I created pull request #760 for fixing this.
