### ISSUE TITLE
Can we configure insecure registries in arquillian

### ISSUE THREAD

**Issue by RajAsapu** [arquillian/arquillian-cube#737]
Hi ,
I have a scenario where i have to implement pulling from internal registry.But it is not allowing me to pull images because of certificate issue.Using docker i set a registry to be insecure registry and pull the images using docker pull command.I would like to know if we have such option in arquillian.

**Comment by lordofthejars** [comment]
This relay on docker-java support, I ll need to check its page

**Comment by lordofthejars** [comment]
I have not seen any property in `docker-java`. Can you ask at https://github.com/docker-java/docker-java how `docker-java` can connect in an  insecure way?

**Comment by RajAsapu** [comment]
Okay sure @lordofthejars will talk to them Thanks
