### ISSUE TITLE
Add DockerDescription support

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#74]
In some days we will have a new ShrinkWrap descriptor for creating Dockerfile files using Shrinkwrap descriptors.  We can use it in containerless module to create the dockerfile inside test instead of using dockerfile.template file.

This implies changing the logic behind containerless so if a Dockerfile and a Dockerfile.template file are in same directory the Dockerfile.template file takes precedence.

In tests we should use:
```
@Deployment public static Descriptor deploy() { Descriptors.create(DockerDescriptor.class)...} 
```

**Comment by aslakknutsen** [comment]
depends onhttps://github.com/shrinkwrap/descriptors-docker/issues/5

**Comment by gastaldi** [comment]
ShrinkWrap Descriptors Docker 1.0.0-alpha-1 is now released

**Comment by lordofthejars** [comment]
Cool now we can start working on this :)

**Comment by aslakknutsen** [comment]
During a prototype to support DockerDescriptors; https://gist.github.com/aslakknutsen/2fc3470cd72ba54e5901 we've come to the realization that we probably need a CubeDescriptor wrapper. There are many settings that are needed not described in the Dockerfile to setup a cube. We could support a very simple v of the 'pure' DockerDescriptor, but for more advanced setups we need a CubeDescriptor.

```java
@Deployment
public static Descriptor create() {
  return Descriptors.create(CubeDescriptor.class)
     .buildImage()
        .using(
          Descriptors.create(DockerDescriptor.class)
            .from("X/y")
            .expose(80)
            .cmd("java", "-jar", "my.jar", "org.test.Test")
        )
        .using(
          ShrinkWrap.create(JavaArchive.class, "my.jar")
            .addPackage(true, "org.test")
        )
     .await().polling()
     .portBindings().add(8080, 80)
     .links().add('databse');
}
```

**Comment by lordofthejars** [comment]
yes that would be really helpful
