### ISSUE TITLE
Openshift doesn't support annotations on project

### ISSUE THREAD

**Issue by jwendell** [arquillian/arquillian-cube#740]
Currently Openshift doesn't support adding labels or annotations to a project (https://github.com/openshift/origin/issues/10315 https://github.com/openshift/origin/issues/3819).

That's why the tests logs are full of warnings like this:
`Could not annotate namespace: [xyz] with status: [PASSED].`

I'm wondering if we should change [`annotate()`](https://github.com/arquillian/arquillian-cube/blob/37280a0618b29fc620f7db51df464543b7a6de35/openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/namespace/OpenshiftNamespaceService.java#L114) method to make it a NOOP when running in Openshift...

**Comment by lordofthejars** [comment]
yes, at least to not confuse users.
