### ISSUE TITLE
Hanging connections on PortForwarder

### ISSUE THREAD

**Issue by spolti** [arquillian/arquillian-cube#752]
##### Issue Overview

Arquillian-cube's port forwarder has a little problem when the connection has issues.
there is a CountDownLatch that is not counted down in case of issues in the connection leading the pf thread to wait indefinitely:
`
"PortForwarding for ddd-239f034c-436b-40c2-a86e-516c30c67bf6/testrunner task-3" #266 prio=5 os_prio=0 tid=0x00007f28f8001800 nid=0x5ddd waiting on condition [0x00007f295dbda000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000697a407f0> (a java.util.concurrent.CountDownLatch$Sync)
...
at org.arquillian.cube.kubernetes.impl.portforward.PortForwardServerConnection.startForwarding(PortForwardServerConnection.java:120)
`
##### Expected Behaviour
The errorComplete needs to be counted down also in case of connection problems.

**Comment by spolti** [comment]
@lordofthejars if you are planning to make a new release of arquillian-cube please wait until I send a fix for this, I just doing a couple of more tests (trying to reproduce again, since I couldn't find a exact step to reproduce it) to make sure it is fixed.

**Comment by lordofthejars** [comment]
Sure :)
