### ISSUE TITLE
[Cube-Docker] Add support for building images that reference an image from a private registry

### ISSUE THREAD

**Issue by georgwolf** [arquillian/arquillian-cube#768]
##### Issue Overview

Building Docker images based on an image from a private registry fails with
`com.github.dockerjava.api.exception.DockerClientException: Could not build image: Get https://[...]/manifests/latest: no basic auth credentials`

##### Expected Behaviour
Registry settings from arquillian.xml docker extension are used for build too.

##### Steps To Reproduce
1. Build an image with a FROM that references an image from a private repository that hasn't been pulled yet

**Comment by lordofthejars** [comment]
Have you tried to configure all credential things in `arquillian.xml`, in theory same mechanism should be used

**Comment by georgwolf** [comment]
Yes, pulling that same image works but building from it does not.
I checked with the debugger and the java-docker lib does use the registry settings from the DockerClientConfig for pulling and pushing images by default but it doesn't use them for building.
This requires explicitly setting them via BuildImageCmd#withBuildAuthConfigs.

I'll create a PR for this.

**Comment by lordofthejars** [comment]
Great!!! Thank you very much for your investigations.
