### ISSUE TITLE
NPE when getting default admin port

### ISSUE THREAD

**Issue by jensstn** [arquillian/arquillian-cube#789]
core/src/main/java/org/arquillian/cube/impl/client/container/ContainerConfigurationController.java:getDefaultPortFromConfigurationInstance can throw a NullPointerException when calling invoke on the Method returned by ```fieldName.getReadMethod()``` (L.105).
This has been observed running against a glassfish-remote-container.

**Comment by bartoszmajsak** [comment]
Any idea why it throws `NPE`?

**Comment by jensstn** [comment]
i didn't have time to dig a lot deeper and it's been a few days, but as far as i remember it happens because it finds a PropertyDescriptor which only has a write method.
do you want me to dig further?

**Comment by bartoszmajsak** [comment]
If you could afford some time for figuring it out that would be awesome. Thanks a lot for your contribution!

**Comment by lordofthejars** [comment]
I close the issue because I have merged the PR, but of course if you have time it is still interesting to know why this was null. I just merge the PR so we can release a new version with this fix.
