### ISSUE TITLE
Remove requirement to specify URL in arquillian config if defined on the user's system

### ISSUE THREAD

**Issue by tnine** [arquillian/arquillian-cube#80]
As outlined in #78 to get cube to function with boot2docker you have to maintain the URL in 2 places.  I'm creating this issue as a tracking issue for easier configuration.  Currently I have to define my URL in the properties for the client, as well as arquillian.xml.  Ideally, I would like to only need to define it in a single location.

**Comment by lordofthejars** [comment]
docker.io.properties would not be required when we add support for ssl in arquillian.xmlm which is what we are currently focus, so all properties will be only placed in one place. Now you need to define twice because using docker.io.properties is required as a workaround.

**Comment by mgreau** [comment]
@tnine have you try to use a Maven property in order to define the URL in a single location like below ?

```
mvn test -Ddocker.io.url=https://192.168.59.104:2376 
```

```
...
<extension qualifier="docker">
        <property name="serverUri">${docker.io.url}</property>
...
</extension>
...
```

**Comment by tnine** [comment]
@mgreau Yes. This issue is not using https in the url.  Rather, it is an issue with the client.  The client needs to know which directory your certificates are in to utilize them.  There's no mechanism to do this currently, so using the driver's native configuration options seems to be the only workaround.

**Comment by lordofthejars** [comment]
I am working on this, in next release you will not require this anymore
El dt., 3 de febr., 2015 a les 4.33 Todd Nine <notifications@github.com> va
escriure:
