### ISSUE TITLE
Can't set alwaysPull when using Compose format

### ISSUE THREAD

**Issue by georgwolf** [arquillian/arquillian-cube#800]
##### Issue Overview
Compose format doesn't have alwaysPull option and it cannot be overridden via cubeSpecificProperties (is ignored).

##### Expected Behaviour
Allow specifying alwaysPull through cubeSpecificProperties.

**Comment by lordofthejars** [comment]
Thank you very much inestimable help. You deserve a 🍺 if we ever meet in a conf.

**Comment by bartoszmajsak** [comment]
@lordofthejars we just have to make sure it's a really good one :)

**Comment by georgwolf** [comment]
Thanks, sounds good ;)
