### ISSUE TITLE
The FeedbackProvider service in Openshift should also include information about builds

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#813]
The idea of the FeedbackProvider is to extract useful information about the environment and display it back to the user in case of an environment timeout.

At the moment we display:
- logs
- events
for the pods that caused the actual timeout.

It probably makes sense for Openshift to expand on this idea and also include build logs.

**Comment by jwendell** [comment]
Notice that since 1.9.0 one can set `logs.copy` to `true` and cube will gather all logs, for all pods (including builds) and openshift events.

**Comment by lordofthejars** [comment]
So we can close this?
