### ISSUE TITLE
Openshift: other goodies from CE-Arq

### ISSUE THREAD

**Issue by Ladicek** [arquillian/arquillian-cube#814]
There's https://github.com/arquillian/arquillian-cube/issues/467 for porting `@Template` from CE-Arq and https://github.com/arquillian/arquillian-cube/issues/468 for porting `@OpenShiftResource`. These are probably the most important bits, but there's a bunch of other things in CE-Arq that could be valuable. See https://github.com/jboss-openshift/ce-arq/tree/master/api/src/main/java/org/jboss/arquillian/ce/api

I'm specifically thinking about:

- [ ] `@AddRoleToServiceAccount`
- [ ] `@ExternalDeployment` (though not sure what exactly that is)
- [ ] `@MountSecret`
- [ ] `@Replicas` (again not exactly sure what this is)
- [ ] `@RoleBinding` (I wonder how `@AddRoleToServiceAccount` compares to this)
- [ ] `@RunInPod` (again not exactly sure what this is)
- [ ] `@RunInPodDeployment` (again not exactly sure what this is)

I'm filing this for tracking, as the CE-Arq bits seem quite useful.

CC @alesj

**Comment by alesj** [comment]
@Replicas - explicitly set more pod relicaps
@RunInPod -- similar to @RunAsClient, but it deploys and runs the tests in a side-car / pod
@RunInPodDeployment -- you can explicitly construct an archive with the tests

**Comment by lordofthejars** [comment]
That's really great, I will suggest to send on PR for each new feature so
it is easier to track and we can always release new version at any stage.
What is also important is to keep documentation updated.

Any help you need please ping me.

Alex

**Comment by Ladicek** [comment]
I might have been unclear, but I currently don't have the capacity to implement/migrate this myself. So please don't expect PRs from me :-)

**Comment by lordofthejars** [comment]
Ok then you mean that we should contact ce team right. It is perfect since
we didn't know about these features.

Thanks

**Comment by Ladicek** [comment]
Yea I think so. But https://github.com/arquillian/arquillian-cube/issues/467 and https://github.com/arquillian/arquillian-cube/issues/468 are more important IMHO.

**Comment by Ladicek** [comment]
I split this into #820, #821, #822, #823, #824, #825 and #826.
