### ISSUE TITLE
Make tests work on Openshift and Kubernetes without changes

### ISSUE THREAD

**Issue by nicolaferraro** [arquillian/arquillian-cube#815]
We were using fabric8-arquillian in quickstarts and now we are switching to Arquillian Cube Kubernetes.
I've managed to migrate [one quickstart](https://github.com/fabric8-quickstarts/spring-boot-camel) by just changing the dependencies in the `pom.xml` file.

However, previously tests were working without changes on both Openshift and Kubernetes, while now:

**On Openshift**
The project should depend explicitly on `arquillian-cube-openshift`.
An additional flag must be used (`enableImageStreamDetection=true`) to ensure that imagestreams are correcly created in the testing project. I've put it in the [surefire configuration for simplicity](https://github.com/fabric8-quickstarts/spring-boot-camel/blob/8735321adb8b5253bc91a16d55ee80c7d702f2fe/pom.xml#L131).

**On Kubernetes**
*Need not* to depend on `arquillian-cube-openshift`, but on `arquillian-cube-kubernetes`. The sole dependency on `arquillian-cube-openshift` turns on a "openshift mode".
*Need not* to detect image streams.

It would be better if:
- `arquillian-cube-openshift` can detect if we are connected to a standard kubernetes cluster and delegate to `arquillian-cube-kubernetes` (that is imported transitively) all processing steps.
- The `enableImageStreamDetection` flag can be defaulted to `true` when running on Openshift.

If this is ok, I can work on it.

Also: it is not related to this PR, but since you had problems with failsafe in #743 , I can tell you that surefire works like a charm.

**Comment by Ladicek** [comment]
Ad `enableImageStreamDetection`, that was changed in 1.9.0 per the discussion in https://github.com/arquillian/arquillian-cube/issues/743 and I'd probably be fine with it defaulting to `true`. (Also the Failsafe issues in https://github.com/arquillian/arquillian-cube/issues/743, the only thing I remember is that Cube was enabled in Surefire, which I didn't want, and I solved that by manually excluding Cube from Surefire's test classpath, which I'm comfortable with.)

**Comment by lordofthejars** [comment]
Love this improvement.
