### ISSUE TITLE
DockerClientException: Could not build image: null when building from dockerfile

### ISSUE THREAD

**Issue by mbrasier** [arquillian/arquillian-cube#829]
##### Issue Overview
When building a docker image from a dockerfile, a `DockerClientException: Could not build image: null
` is thrown, this appears to be caused by using an old version of docker-java, as it is a fixed bug in the latest versions.

##### Expected Behaviour
No exception is thrown

##### Current Behaviour
```
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: null
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:71)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
	at org.arquillian.cube.docker.impl.docker.DockerClientExecutor.buildImage(DockerClientExecutor.java:738)
```

##### Steps To Reproduce

Use a dockerfile to build an image:

```
        <property name="dockerContainers">
            unit-test:
                buildImage:
                    dockerfileLocation: src/test/docker/unit-test
                    noCache: true
                    remove: true
                await:
                    strategy: sleeping
                    sleepTime: 30 s
                portBindings: [1090->1080/tcp, 9999/tcp, 8080/tcp]
                restartPolicy:
                    name: failure
                    maximumRetryCount: 1
                manual: false
```

##### Additional Information

See [https://github.com/docker-java/docker-java/issues/860](https://github.com/docker-java/docker-java/issues/860) for related docker-java issue

**Comment by lordofthejars** [comment]
Can you provide a github project so we can take a look?

**Comment by mbrasier** [comment]
I will put something together next week.

**Comment by lordofthejars** [comment]
Great, thank you very much, since I am not sure what is happening because we have tested this use case as well (or at least with the description) then I am not sure what is happening. Then with an example I will be able to debug, fix it in cube or provide you a solution on your example

**Comment by mbrasier** [comment]
It seems to be an issue with the latest version of docker, which doesn't work with the older version of docker-java that arquillian-cube (at least the version in the latest arquillian-universe BOM) uses. Tracing through, docker outputs a string "Successfully tagged" when the image is created, but docker-java is looking for the string "Successfully created" and so assumes that creation of the container failed. It may be you start seeing the issue if you updated to the latest docker release.

**Comment by lordofthejars** [comment]
Then assuming that latest `docker-java` has fixed, you can update the version on your pom and try it.

**Comment by mbrasier** [comment]
Yes that works, but this ticket is to ensure that arquillian-cube updates its dependency (having a dependency on docker-java in our project isn't great, because we don't depend on it, other than to fix arquillian-cube).

**Comment by lordofthejars** [comment]
ok, then it is easy, thanks:) I'll do it now.
