### ISSUE TITLE
Provide a ‘oc’ command proxy

### ISSUE THREAD

**Issue by cescoffier** [arquillian/arquillian-cube#830]
I often need to execute ‘oc’ commands (such as ‘oc create -f ..., or oc new-app ...) in my test. Most of the time it’s to execute the exact same instructions we give to our user and so check that the doc is still valid.

It would be great to have a utility class calling ‘oc’ behind the scene. For instance, method allowing to execute oc command, retrieve the result (status) and output (StrIng or byte[]).

I can also see more and more usage of such a feature with the service catalog (with the new bind and unblind commands).

**Comment by lordofthejars** [comment]
Just one thing, when you mean running `oc` you mean just pass an string with arguments of `oc` or you want to have it in a DSL approach? The latter on seems so complicated.

**Comment by cescoffier** [comment]
Let's do something simple @lordofthejars: 

```
ExecResult res = oc.execute("create -f mytemplate.yaml");
assertThat(res).succeed().outputContains("bla bla bla");
```

So we can just copy and paste our commands.

**Comment by lordofthejars** [comment]
ok perfect, thanks

**Comment by lordofthejars** [comment]
Probably for this issue, more than implementing an integration/wrapper around CLI calls, I think it wil be better to document how to use Arquillian Spacelift in tests.
