### ISSUE TITLE
Arquillian Kube recipes

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#834]
Create a section in documentation with common recipes for Kubernetes and OpenShift.
To give some ideas:

- [x] Deploy kubernetes app and test it.
- [x] Deploy OpenShift app and test it using `@RouteUrl` enrichment
- [x] Deploy Kubernetes app and test it using fabric8-kubernetes assertj custom assertions
- [x] OpenShift + Fabric8 example 
- [x] OpenShift + Templates example

**Comment by lordofthejars** [comment]
I have created an example https://github.com/lordofthejars/rest-springboot-openshift where it is used OpenShift + Fabric8 + Spring Boot + `@RouteUrl`

This project can be used as a base for all other use cases.

**Comment by hemanik** [comment]
Example for Kubernetes Deployed App: https://github.com/hemanik/kubernetes-deployment-testing

**Comment by bartoszmajsak** [comment]
- [ ] transfer to `arquillian-microservices` org
- [ ] blog post about this
- [ ] link in the docs (simple static link - think about automation (adoc extension or whatever))
