### ISSUE TITLE
Use `@Repeatable` annotations in OpenShift annotations

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#851]
##### Issue Overview

Some annotations such as `@Templates`, `@OpenShiftResources, ... does not using `@Repeatable` approach.

##### Expected Behaviour

Implement annotations with `@Repeatable`

##### Current Behaviour

Uses old way (prior to Java8)

**Comment by Ladicek** [comment]
Also the names of the wrapper annotations are inconsistent. I propose that the wrapper annotation should be a simple english plural of the wrapped annotation (e.g. `@Template` and `@Templates`).

I'm aware of 2 annotations that violate this:
- `@AddRoleToServiceAccount` and `@AddRoleToServiceAccountWrapper` (can be fixed as part of #854)
- `@Template` and `@TemplateResources`
    - Though this case isn't a simple wrapper, there's another parameter `syncInstantiation`. I don't quite understand its purpose (CC @alesj @jwendell), but even if we don't make `@Template` repeatable, we still might want to rename `@TemplateResources` to `@Templates`.
