### ISSUE TITLE
Study HTTP Client abstractions

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#853]
##### Issue Overview

Currently in OpenShift module we are using two Http client abstractions, `HTTPClient`
 and `okhttp`. Study if we can use only once in all cases.

(https://github.com/arquillian/arquillian-cube/pull/849#discussion_r151382882)

##### Expected Behaviour

Only one Http Client used.

##### Current Behaviour

`HTTPClient` from Apache commons and `okhttp` are used.

**Comment by Ladicek** [comment]
Related: the CE-Arq migration brought in an entire module, `openshift/httpclient`, that provides yet another HTTP client abstraction (implemented using Apache HTTP Client). IMHO, that module should be removed without replacement.

**Comment by lordofthejars** [comment]
Yes I have noticed here there are several abstractions, and I have pointed out in https://github.com/arquillian/arquillian-cube/pull/849#discussion_r151382882 that it could be removed by using kubernetes client.

**Comment by lordofthejars** [comment]
After removing code where Apache Http Client is used, now only `okhttp` client is used in all code. 
Http client is required for some extra configuration steps such as Jolokia.
