### ISSUE TITLE
@RoleBinding and @AddRoleToServiceAccount could be merged

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#854]
##### Issue Overview

the `@RoleBinding` and `@AddRoleToServiceAccount` annotations should IMHO be merged to one

##### Expected Behaviour

`@RoleBinding` and `@AddRoleToServiceAccount` merged into one.

##### Current Behaviour

There are two different annotations.

**Comment by lordofthejars** [comment]
@Ladicek Do you have any example of usage of `@RoleBinding` and `@AddRoletoServiceAccount` so we can see how it can be merged into one annotation?

**Comment by Ladicek** [comment]
I couldn't fine a usage of `@AddRoleToServiceAccount` on the entire GitHub, but here are some usages of `@RoleBinding`: https://github.com/jboss-openshift/ce-testsuite/search?q=RoleBinding In fact, some of them actually add a role to a service account, probably predating the existence of `@AddRoleToServiceAccount`. E.g. https://github.com/jboss-openshift/ce-testsuite/blob/master/eap/eap70/src/test/java/org/jboss/test/arquillian/ce/eap70/Eap70ClusteringTest.java

**Comment by lordofthejars** [comment]
@alesj Any feedback regarding this?

**Comment by alesj** [comment]
There was a reason for this, but cannot remember atm.
@luksa? (with your notoriously "good" memory 😋)

**Comment by alesj** [comment]
This - - as in this split, why we have two.

**Comment by Ladicek** [comment]
My guess is that you somehow need to distinguish between regular user and service account when creating the role binding, but you could have a boolean flag for that, or two different annotation attributes (which would require runtime checks that only one is present). If you think that having two different annotations is better, well at least we could unify their naming :-)

**Comment by Ladicek** [comment]
Given that this would now be a breaking change, I'm in favor of closing this.
