### ISSUE TITLE
Creates @KubernetesResource to set resources in K8s cluster

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#874]
##### Issue Overview

Currently we have `@OpenShiftResource` annotation for setting resources for each test.
We could implement the same feature but for Kubernetes. 

@jwendell @alesj Do you think it is worth to implement it? I think we cannot generialize because the openshift ones requires the `OpenshiftClient`

**Comment by jwendell** [comment]
Most of our usages of @OpenshiftResource are for creating generic resources - which are also part of kubernetes. I believe the [long term] goal is to have all of them available directly in kubernetes. See for example the RBAC stuff: https://kubernetes.io/docs/admin/authorization/rbac/

So, I'm +1 in support them in cube, and probably in the future deprecate those Openshift specific features, following the Openshift roadmap.
