### ISSUE TITLE
Sets localhost URI when unix socket used

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#88]
Sets localhost URI when unix socket used. Currently the IP of the docker server is got from configuration file. If unix socket is used then we need to set to localhost.

**Comment by aslakknutsen** [comment]
If you read back dockerClientConfig.getUri after calling DockerCmdExecFactoryImpl.init it will update that Uri to be the sanitized version of the unix socket uri, meaning localhost:80. The port number makes no sense, but.. 

Perhaps just as easy to just do if schema == unix:: as it would be to rely on a internal impl detail.. ;)

**Comment by lordofthejars** [comment]
my idea was that something like if URI protocol is unix:// then localhost

**Comment by aslakknutsen** [comment]
yea, just as well
