### ISSUE TITLE
Create maven profiles to start docker tests or k8s/openshift tests on travis CI.

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-cube#886]
##### Issue Overview
There is no different profiles for different env. We can create parallel configuration by enabling `env in [docker, k8s/openshift]`. So just run k8s & openshift tests in parallely with travis matrix when env k8s is enabled & docker in another job.

This will reduce build time

**Comment by bartoszmajsak** [comment]
Together with `@RequireOpenshift` let's use `@Category(RequireOpenshift.class)` (to keep backward compatibility for now) + use smart-testing categorized strategy.

If that would fail let's decouple requirement and resolver/logic by using SPI instead of meta-annotation as it's done now.

**Comment by dipak-pawar** [comment]
I think we don't really need categorized strategy from smart testing here. So  I am not adding smart testing categorized strategy here
