### ISSUE TITLE
Add operation for getting files from container

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#89]
Adds operation in Cube interface for getting files from running container. With this devs will be able to get files from container in the test by using Cube interface.

Also adding anew property in configuration file so before container is stopped by Arquillian Cube a list of files can be copied in output local directory for manual inspection.

**Comment by lordofthejars** [comment]
In this issue we can do it two things:

* The first one by adding `copyFileFromContainerCmd` method to DockerClient so it can be used by users.
* The second one by adding an attribute to arquillian.xml which you can set an array of files to be copied just before stopping the container and the where to copy in local disk, so it can be inspected after execution.

**Comment by aslakknutsen** [comment]
@lordofthejars I think this follow the same logic as https://github.com/arquillian/arquillian-cube/issues/90#issuecomment-72811634

**Comment by lordofthejars** [comment]
Yes exactly the same.
