### ISSUE TITLE
Create KubernetesAssistant class

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#897]
##### Issue Overview

Create `KubernetesAssistant` class similar to `OpenshiftAssistant` class.

##### Expected Behaviour

Create `KubernetesAssistant` class to allow deploy Kubernetes resources.

##### Current Behaviour

There is no class to allow this.

**Comment by bartoszmajsak** [comment]
Relevant PR which brought `OpenShiftTestAssitant` https://github.com/arquillian/arquillian-cube/pull/893.

Next step - refactoring to unify both assistants as they share common behaviour (something to discuss)

**Comment by hemanik** [comment]
Pending Next Step 

- [ ]  refactoring to unify both assistants as they share common behaviour (something to discuss)
