### ISSUE TITLE
Add @Template annotation in test method scope

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#933]
##### Issue Overview

Add `@Template` annotation in test method scope.

##### Expected Behaviour

Allow defining `@Template` at method level, so the template is applied before executing the method and everything applied from that template removed after the test method.

##### Current Behaviour

`@Template` only works at class level

**Comment by bartoszmajsak** [comment]
In case of having `@Template` defined on both class and method level I believe we should deploy them to the narrowest scope - so the test namespace, right?

**Comment by lordofthejars** [comment]
I think that if `@Template` is defined at class level and method level is something independent.  I mean you can define a template at class level which might be something global for the whole test class, but then you might want to create a specific template for each test method.

For example:

```
@Template("java_service_template.json")
public class Persistence {
  @Test
  @Teamplate("myssql_template.json)
  public void should_run_with_mysql() {}

  @Test
  @Teamplate("postgresql_template.json)
  public void should_run_with_postgresql() {}

}

Notice that we are not saying that they are mutually exclusive.

**Comment by lordofthejars** [comment]
About namespaces for now is something we should not take care at all since we are not supporting it yet. You only reuse a namespace or create a new one the suite. When we implement the multiple namespace features then we could take care of all of this. Right?
