### ISSUE TITLE
Login to openshift/Kubernetes cluster before starting execution of tests

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-cube#964]
Investigate is there any option for authentication with proper permission to openshift/kubernetes cluster while running arquillian cube tests

Parent task https://github.com/arquillian/arquillian-organization/issues/26

**Comment by dipak-pawar** [comment]
We can run tests using system properties `-Dkubernetes.master=cluster_url` and `-Dkubernetes.auth.token=TOKEN` to authenitcate to openshift/k8s cluster before executing tests

**Comment by lordofthejars** [comment]
But how about when using from IDE?

**Comment by dipak-pawar** [comment]
We do have way to provide configuration in `arquillian.xml`, but I believe we should not expose token from arquillian.xml.

currently arquillian is looking for any system property with name `kubernetes.auth.token` and `kubernete.master` or env variable with `KUBERNETES_AUTH_TOKEN` and `KUBERNETES_MASTER`. So either set these values somehow before executing tests.

Do you have anything in mind other than this?

**Comment by lordofthejars** [comment]
No, just thinking that would be great to fix it somehow, but probably it means changing how you run tests in Che.

**Comment by dipak-pawar** [comment]
Also most important thing is you need just one time login to cluster, after that you don't need any cluster url or token, because cube will use cluster's current context stored in `~/.kube/config` on client,

**Comment by lordofthejars** [comment]
exactly, so maybe we could do something like in cube we detect if we are in IDE (if we are in IDE probably checking classpath), then we check if there is the authentication file, if not then we can show a console message where user can introduce the token to authenticate. It is like a wizard but in console and just in case of being inside IDE.

**Comment by dipak-pawar** [comment]
Good Idea @lordofthejars. @bartoszmajsak Do you have any thoughts?

**Comment by bartoszmajsak** [comment]
In the context of OSIO switching clusters is not what we should promote (even if possible for the user to do). We have two namespaces we can potentially use to run our tests on:

- `user`
- `user`-stage

where `user` is your username, e.g. `bartosz-1` in my case.

**Comment by dipak-pawar** [comment]
I am not sure should we use `user-stage` namespace to run our tests, because it's created by `devtools-sre ` and I am not sure about it's purpose. But definitely we can run tests in `user` namespace.

Now about switching cluster context, when you are inside osio, I think different user may belongs to different cluster. So We should ask for user which cluster are you on? or atleast using some api we need to fetch it to use it for single time login

**Comment by bartoszmajsak** [comment]
> I am not sure should we use user-stage namespace to run our tests, because it's created by devtools-sre and I am not sure about it's purpose. But definitely we can run tests in user namespace.

It's somewhat of a `stage` environment where you can deploy your apps from Jenkins pipeline.

> Now about switching cluster context, when you are inside osio, I think different user may belongs to different cluster. So We should ask for user which cluster are you on? or atleast using some api we need to fetch it to use it for single time login

There is a proxy rolled out lately for this purpose.

**Comment by bartoszmajsak** [comment]
As the PR is closed can we close that one too @dipak-pawar? Or is there anything to follow-up based on the PR review?

**Comment by dipak-pawar** [comment]
@bartoszmajsak, As we don't have anything to follow-up based on review. I am closing this.
