### ISSUE TITLE
Bug: wrong parsing of env.dependencies

### ISSUE THREAD

**Issue by pavolloffay** [arquillian/arquillian-cube#967]
Doc says that `env.dependencies` is a comma-separated list, however comma is placed at the end of an element, then it fails to load resource file.

**Comment by lordofthejars** [comment]
Sorry can you provide an example, I am not sure if I am understanding you correctly.

Thanks

**Comment by pavolloffay** [comment]
Try,

```xml
<?xml version="1.0"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://jboss.org/schema/arquillian"
            xsi:schemaLocation="http://jboss.org/schema/arquillian
    http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

  <extension qualifier="kubernetes">
    <property name="env.dependencies">file1,file2</property>
  </extension>
</arquillian>

```

Whether it parses two URLs correctly.

**Comment by lordofthejars** [comment]
According to documentation the `env.dependencies` must be of type URL, and `file1` or `file2` are not a valid URL, I suspect this is the problem you are encountering now.

**Comment by lordofthejars** [comment]
I can confirm that unit test passes with your input.

**Comment by pavolloffay** [comment]
Hhere is a reproducer https://github.com/jaegertracing/jaeger-kubernetes/blob/master/production-elasticsearch/src/test/resources/arquillian.xml#L23. Remove the space and add `,`. 

Then run `./mvnw clean verify -Pelasticsearch`. Do not forget to start minikube before.

**Comment by lordofthejars** [comment]
I have run the unit test with your configuration file and it worked, currently I am involved in some issues, but if you can send me the stacktrace I'll take a look quickly to try to find the cause.

**Comment by lordofthejars** [comment]
Also I have seen you are using cube 1.9.  The comma separated value was added in 1.13.0 http://arquillian.org/blog/2018/01/18/arquillian-cube-1-13-0/ so you need to update the dependency as well.

**Comment by pavolloffay** [comment]
I thought so, I wanted to update but there were some dependency issues I run into. @lordofthejars thanks.
