### ISSUE TITLE
Openshift templates, should be passed a default set of parameters, like scripts do.

### ISSUE THREAD

**Issue by iocanel** [arquillian/arquillian-cube#969]
Sometimes that are parameters passed to the openshift template, that are relative to the target environment (e.g. the project name: https://github.com/syndesisio/syndesis/blob/master/app/deploy/syndesis-restricted.yml#L31)

To deal with this cases in the past, we used to arquillian managed property values as environment variables to scripts. (See: https://github.com/arquillian/arquillian-cube/blob/0d6d2d758f71bd8a474ce33281cfa0609a2708c1/kubernetes/kubernetes/src/main/java/org/arquillian/cube/kubernetes/impl/SessionManager.java#L513-L513) 

We should do the same in the OpenshiftResourceInstaller.

**Comment by lordofthejars** [comment]
@iocanel are you going to provide a PR or you prefer we work on this?

**Comment by iocanel** [comment]
On 02.06.18, Alex Soto wrote:
>@iocanel are you going to provide a PR or you prefer we work on this?
At the moment I don't have the cycles to create one. So, if you could
work on that, it would be awesome!

Thanks!

**Comment by lordofthejars** [comment]
Is it a blocker for you?

**Comment by iocanel** [comment]
On 02.06.18, Alex Soto wrote:
>Is it a blocker for you?
I have a workaround, so its not!

**Comment by iocanel** [comment]
@lordofthejars: atm, I have some spare cycles, so I'll assign it to myself.
