### ISSUE TITLE
Add boot2docker URI

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#99]
Using Arquillian Cube requires that you set the URI of the docker server. In case of boot2docker it means that you need to run boot2docker CLI command and get the ip. And moreover because it runs in a VM it means that this IP is not static.
To avoid failures because a change on IP of the Docker server, we could create next "URI":

http://${boot2docker}:port

Then in Cube we can see that it is a boot2docker ip and it can execute the boot2docker command, resolve the ip and add in the URI.
Note that this also implies to add a property to set the boot2docker installation directory.

**Comment by aslakknutsen** [comment]
boot2docker is not auto added to 'path' ?

**Comment by aslakknutsen** [comment]
Wondering if "http://boot2docker" would be enough. 

Thinking avoid using ${} to not confuse with property replacement in either Maven or Arquillian. Should be ok to set via command line -Ddocker.serverUri=http://boot2docker

The port should be auto fetchable as well.

**Comment by lordofthejars** [comment]
yes probably better without the ${}
