### ISSUE TITLE
arquillian.xml properties should be injectable in RouteURL annotation

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#996]
##### Issue Overview

Expression resolver should be able to resolve this property defined in `arquillian.xml` if it's used to inject variable in test like `@RouteUrl("{app.name}")`

##### Expected Behaviour

Properties defined in `arquillian.xml` can be injected as `@RouteUrl` property

##### Current Behaviour

Not supported

**Comment by bartoszmajsak** [comment]
We should look if this functionality of generic key-value config pairs is available in core so we can simply pass it to `@RouteUrl` provider. If not we should enhance core.
